'use strict';
(() => {
const D=window.SITE_DATA,C=D.config,$=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const stages=['cabinet','flora','studio','archive'].includes(C.theme)?['青葉','色づき始め','黄葉進行','見頃','落葉始め','落葉']:C.fixed?['青葉','開始變色','黃葉進行','見頃','開始落葉','落葉']:['青葉','開始轉黃','黃葉進行','最佳觀賞期','開始落葉','落葉'],ja=['青葉','色づき始め','黄葉進行','見頃','落葉始め','落葉'],colors=['#347a4a','#91a851','#b0a235','#cfa228','#9f6440','#767368'];
const state={species:'ginkgo',q:'',region:'',status:'',grade:'',type:'',free:false,avenue:false,sort:'region',kind:'',selected:null,route:[],favorites:[],visited:[],demo:!!C.fixed,demoDate:'2026-11-23',view:'explore',layout:'both',road:null};
let map,markerLayer,routeLayer,lastSize,needsFit=false,timer,tileErrors=0,storageFailed=false,restoreFocus,music,musicTimer,musicPlaying=false,lottery=[];
const leafIcon='<svg viewBox="0 0 36 42" width="25" height="29" aria-hidden="true"><path d="M18 31 Q-9 12 6 3 Q13-4 18 6 Q24-4 31 3 Q46 12 18 31Z" fill="currentColor"/><path d="M18 30V41" stroke="currentColor" stroke-width="2"/></svg>';
const key='tokyo-autumn-'+C.theme+'-v1';
if(C.store)try{const v=JSON.parse(localStorage.getItem(key)||'{}');for(const k of ['route','favorites','visited'])state[k]=Array.isArray(v[k])?v[k].filter(id=>D.places.some(p=>p.id===id)):[];state.route=state.route.slice(0,C.maxStops||26);}catch{storageFailed=true;}
function save(){if(!C.store)return;try{localStorage.setItem(key,JSON.stringify({route:state.route,favorites:state.favorites,visited:state.visited}));}catch{storageFailed=true;notify('本機儲存不可用，操作僅保留於本次瀏覽。');}}
function notify(s){$('#toast').textContent=s;clearTimeout(notify.timer);notify.timer=setTimeout(()=>$('#toast').textContent='',4500);}
const link=(u,t)=>/^https?:\/\//.test(u||'')?`<a href="${esc(u)}" target="_blank" rel="noopener noreferrer">${esc(t||u)}</a>`:'來源未提供';
const opts=(vs,t)=>`<option value="">${t}</option>`+[...new Set(vs)].filter(Boolean).sort().map(v=>`<option value="${esc(v)}">${esc(v)}</option>`).join('');
function stage(p){if(!state.demo)return null;const n=(new Date(state.demoDate+'T12:00:00Z')-new Date('2026-11-23T12:00:00Z'))/86400000;return n<-28?0:n<-14?1:n<0?2:n<6?3:n<10?4:5;}
const label=p=>stage(p)===null?C.status:stages[stage(p)],badge=p=>`<span class="badge ${state.demo?'demo':''}">${esc(label(p))}${state.demo?' · 示意':''}</span>`;
function visible(){if(C.speciesSwitch&&state.species==='cherry')return [];return D.places.filter(p=>(!state.q||(p.name_zh+' '+p.name_ja+' '+p.area).toLowerCase().includes(state.q.toLowerCase().trim()))&&(!state.region||p.regionLabel===state.region||p.area===state.region)&&(!state.status||label(p)===state.status)&&(!state.grade||p.source.grade===state.grade)&&(!state.type||p.type===state.type)&&(!state.free||/^無料/.test(p.facts.fee||''))&&(!state.avenue||p.type==='銀杏大道')&&(!state.kind||sourceType(p.source)===state.kind)).sort((a,b)=>state.sort==='status'?label(a).localeCompare(label(b),'zh-Hant'):a.regionLabel.localeCompare(b.regionLabel,'zh-Hant'));}
function fact(p,k){let v=p.facts[k];return Array.isArray(v)?v.join('；'):v||'來源未提供';}
function sourceType(s){if(C.restricted){if(s.grade==='X')return '失效';if(/forecast|預報|預測/.test(s.role))return '預測';if(/歷史|過去/.test(s.role)||/202[2-5]/.test(s.evidence_date))return '歷史';if(s.grade==='T')return '民間回報';if(/觀測|實測/.test(s.role)&&['A','O'].includes(s.grade))return '官方觀測';if(/待確認|未確認/.test(s.species))return '待確認';return '候選';}return s.grade==='X'?'失效／排除':/forecast|預報|預測/.test(s.role)?'預報':/歷史|過去/.test(s.role)||/202[2-5]/.test(s.evidence_date)?'歷史／候選':s.grade==='T'?'第三方參考':'來源入口／候選';}
function artwork(){return '<svg class="hero-art" viewBox="0 0 500 230" role="img" aria-label="原創東京秋日示意插畫，非景況照片"><path d="M0 207 Q120 160 230 193 T500 185 V230 H0Z" fill="#d5c377" opacity=".3"/><path d="M260 195 L277 75 L282 195 M261 142H285 M268 102H281 M253 165H291" stroke="#6f7655" fill="none" stroke-width="4"/><path d="M40 192V90 M112 192V77 M397 195V105" stroke="#716342" stroke-width="6"/><g fill="#d8b84c"><path d="M40 112 Q-28 60 40 20 Q108 60 40 112Z"/><path d="M112 102 Q54 55 112 5 Q180 55 112 102Z"/><path d="M397 128 Q337 74 397 39 Q453 74 397 128Z"/></g><path d="M173 189V140H213V189 M330 190V118H365V190" fill="#829080" opacity=".7"/><circle cx="446" cy="49" r="34" stroke="#b69b49" fill="none"/><text x="446" y="60" text-anchor="middle" font-size="30" fill="#786323">秋</text><text x="20" y="225" font-size="11" fill="#797860">原創插畫・示意</text></svg>';}
function shell(){
document.body.className=C.theme;document.title=C.title;
$('#app').innerHTML=`<header class="site-header"><div class="wrap header-inner"><div class="brand"><svg viewBox="0 0 36 42" width="25" height="29" aria-hidden="true"><path d="M18 31 Q-9 12 6 3 Q13-4 18 6 Q24-4 31 3 Q46 12 18 31Z" fill="currentColor"/><path d="M18 30V41" stroke="currentColor" stroke-width="2"/></svg> <span>${esc(C.title)}</span></div><nav class="nav" aria-label="主要導覽"><button data-view="explore">探索</button>${C.calendar?'<button data-view="calendar">葉況日曆</button>':''}${C.favorites||C.passport?'<button data-view="favorites">收藏'+(C.passport?'護照':'')+'</button>':''}${C.route?'<button data-view="walk">散步</button>':''}<button data-view="sources">資料來源</button>${C.motion?'<button id="motion" aria-pressed="true">動畫：開</button>':''}</nav></div></header>
<main id="main" class="wrap"><section class="hero"><div class="hero-copy"><p class="eyebrow">Tokyo · seasonal field notes</p><h1>${C.theme==='night'?'把東京的秋天，<br>收進你的地圖':esc(C.title)}</h1><p>${esc(C.theme==='night'?'從有來源的地點開始，為秋夜留一段慢走的時間。':C.subtitle)}</p><div class="audit"><span>整理：${D.built}</span><span>清冊查核：${D.snapshot}</span><span>${C.fixed?'固定示例日：2026-11-23':'當季實測：尚無'}</span></div><div class="toolbar" style="margin-top:16px"><button class="primary" data-view="explore" data-scroll="workspace">開始探索</button>${C.music?'<button id="music" aria-pressed="false">播放散步音樂</button>':''}</div></div>${artwork()}${C.motion?'<div class="leaf-motion" aria-hidden="true"><i><svg viewBox="0 0 36 42" width="25" height="29" aria-hidden="true"><path d="M18 31 Q-9 12 6 3 Q13-4 18 6 Q24-4 31 3 Q46 12 18 31Z" fill="currentColor"/><path d="M18 30V41" stroke="currentColor" stroke-width="2"/></svg></i><i><svg viewBox="0 0 36 42" width="25" height="29" aria-hidden="true"><path d="M18 31 Q-9 12 6 3 Q13-4 18 6 Q24-4 31 3 Q46 12 18 31Z" fill="currentColor"/><path d="M18 30V41" stroke="currentColor" stroke-width="2"/></svg></i><i><svg viewBox="0 0 36 42" width="25" height="29" aria-hidden="true"><path d="M18 31 Q-9 12 6 3 Q13-4 18 6 Q24-4 31 3 Q46 12 18 31Z" fill="currentColor"/><path d="M18 30V41" stroke="currentColor" stroke-width="2"/></svg></i></div>':''}</section>
<section id="explore-view" class="view"><div id="stats" class="stats"></div><div class="notice">${C.fixed?'固定教學示意：共同採氣象廳東京平年值作圖例，並非各園區實測。':C.restricted?'只用指定試算表；來源入口、預報與歷史文章都不等於當季實測。':'尚無2026年各景點日期實測；目前狀態保留未知，歷史紀錄另行標示。'}</div>${C.speciesSwitch?'<div class="species-tabs"><button data-species="ginkgo" aria-pressed="true">銀杏</button><button data-species="cherry" aria-pressed="false">櫻花</button></div>':''}<div class="legend" id="legend"></div>
${C.demo?'<div class="feature-panel"><div class="toolbar"><button data-mode="source" aria-pressed="true">來源資料</button><button data-mode="demo" aria-pressed="false">示範葉況</button></div><div id="demo-controls" hidden><strong>模擬資料，非實測或預報</strong><p>共同日期模型用於練習介面，不代表不同園區的實際進度。</p><label>示意日期<input id="demo-date" type="range" min="0" max="60" value="44"></label><output id="demo-output">2026-11-23</output></div></div>':''}
<div class="toolbar">${C.map!=='none'&&C.theme!=='night'?'<button role="tab" aria-selected="false" data-layout="map">地圖</button><button role="tab" aria-selected="false" data-layout="list">清單</button><button role="tab" aria-selected="false" data-layout="both" aria-pressed="true">地圖與清單</button>':''}<button class="filter-toggle" aria-expanded="false" id="filter-toggle">展開篩選</button></div>
<div class="workspace" id="workspace"><div class="left-column"><div id="filters" class="filters mobile-closed"><label>搜尋地點<input id="search" type="search" placeholder="中文、日文或地區"></label><label>${['cabinet','studio'].includes(C.theme)?'行政區':'地區'}<select id="region">${opts(D.places.map(p=>['cabinet','studio'].includes(C.theme)?p.area:p.regionLabel),'所有地區')}</select></label><label>葉況<select id="status">${opts([C.status,...stages],'全部狀態')}</select></label>
${['cabinet','flora'].includes(C.theme)?`<label>來源等級<select id="grade">${opts(D.sources.map(s=>s.grade),'全部等級')}</select></label>`:''}${C.fixed?`<label>景點類型<select id="type">${opts(D.places.map(p=>p.type),'所有類型')}</select></label>`:''}${C.theme==='archive'?'<label>排序<select id="sort"><option value="region">地區</option><option value="status">狀態</option></select></label>':''}${C.theme==='cabinet'?'<label class="check-label"><input id="ginkgo-only" type="checkbox" checked>只看銀杏景點</label><p class="small">收錄皆為銀杏地點；取消也不混入非景點來源列。</p>':''}${C.theme==='night'?'<label class="check-label"><input id="free" type="checkbox">來源明列免費</label><label class="check-label"><input id="avenue" type="checkbox">只看銀杏大道</label>':''}<button id="clear-filters">清除篩選</button></div><div class="result-line"><strong id="result-count"></strong><span class="small">點選查看資料</span></div><div id="cards" class="cards"></div></div>
${C.map==='none'?'':`<div class="map-shell" id="map-shell"><div class="map-label">${C.map==='diagram'?'東京區域示意圖 · 版面位置，非地理座標':'OpenStreetMap · 近似座標／園區代表點'}${C.theme==='travel'?' · 資料目前涵蓋東京':''}</div><div class="map" id="map" aria-label="景點地圖"></div><div class="map-footer">${C.map==='diagram'?'點擊景點編號查看名稱與來源。':'© OpenStreetMap contributors · 代表點不是入口或銀杏單株。'}</div></div>`}
${C.theme==='studio'?'<aside class="right-column"><div id="side-detail" class="side-detail" hidden></div><div id="route-mount"></div></aside>':''}</div></section>
<section class="view" id="walk-view" hidden></section><section class="view" id="favorites-view" hidden></section><section class="view" id="calendar-view" hidden></section><section class="view" id="sources-view" hidden></section>
<footer class="site-footer"><p>${esc(C.footer)}</p><p>${link(D.originalSheet,'原始資料表')} · 整理日期 ${D.built} · <button data-view="sources">來源與資料限制</button></p>${!C.restricted?`<p>氣象廳東京平年值：黃葉11/23、落葉12/3（1991–2020）。${link(D.jma.yellowSource,'黃葉')} · ${link(D.jma.fallSource,'落葉')}，不代替園區觀測。</p>`:''}${C.fixed?`<p>資訊架構參考：${link('https://weathernews.jp/s/sakura/','Weathernews さくらCh.')}、${link('https://tenki.jp/kouyou/','tenki.jp 季節情報')}；未複製其圖文或版面。</p>`:''}</footer></main>
${C.theme==='studio'?'<nav class="mobile-nav" aria-label="手機導覽"><button data-view="explore">探索</button><button data-view="walk">散步</button><button data-view="sources">來源</button></nav>':''}
<dialog id="detail"><div class="dialog-top"><strong id="dialog-heading">景點詳情</strong><button id="close-detail">關閉 ×</button></div><div class="dialog-content" id="dialog-content"></div></dialog><div id="toast" class="toast" role="status" aria-live="polite"></div>`;
$('#walk-view').innerHTML=routeMarkup();if(C.theme==='studio')$('#route-mount').append($('#walk-panel'));$('#sources-view').innerHTML=sourcesMarkup();if(C.calendar)$('#calendar-view').innerHTML='<div class="feature-panel"><h2>葉況日曆</h2><label>日期<input type="date" id="calendar-date" value="2026-10-06"></label><div id="calendar-result"></div><h3>通常季節／平年值</h3><p>東京標本黃葉11/23、落葉12/3（1991–2020），不是園區預報。</p><h3>預報</h3><p>清冊保留發布日期與尺度，未取得園區當季日期觀測，不據此覆寫實測。</p></div>';
if(C.restricted){const el=document.createElement('label');el.innerHTML='來源類型<select id="kind">'+opts(D.sources.map(sourceType),'全部來源類型')+'</select>';$('#filters').insertBefore(el,$('#clear-filters'));}if(C.theme==='studio'){const slot=document.createElement('div');slot.id='mobile-search';slot.hidden=true;$('#workspace').before(slot);syncSearch();}bind();render();renderRoute();renderFavorites();if(C.calendar)renderCalendar();initMap();if(storageFailed)notify('本機儲存不可用，收藏與清單僅保留於本次瀏覽。');
}
function routeMarkup(){if(!C.route)return '';let f='';
if(C.route==='recommend')f=`<div class="form-grid"><label>區域<select id="rec-region">${opts(D.places.map(p=>p.regionLabel),'所有區域')}</select></label><label>想看狀態<select id="rec-status">${opts(stages,'任何示意狀態')}</select></label><label>預計時間<select id="rec-budget"><option value="60">1小時</option><option value="120">2小時</option><option value="240">半日</option></select></label><label>偏好<select id="rec-preference"><option value="nature">自然散步</option><option value="photo">攝影</option><option value="garden">庭園</option></select></label></div><button id="recommend" class="primary">產生示意路線</button><p class="small">預算只安排建議停留；移動時間未計入，不是即時導航。</p>`;
if(C.route==='roads')f=`<div class="form-grid two"><label>起點方式<select id="origin-kind"><option value="place">景點代表點</option><option value="manual">手動座標</option><option value="station">車站（外部導航）</option><option value="geo">我的位置（需同意）</option></select></label><label>起點<select id="origin-place">${D.places.map(p=>`<option value="${p.id}">${esc(p.name_zh)}</option>`).join('')}</select></label><label>緯度<input id="origin-lat" type="number" step="any" placeholder="35.7"></label><label>經度<input id="origin-lng" type="number" step="any" placeholder="139.7"></label><label>起點／終點車站<input id="origin-station" placeholder="車站名稱交由外部地圖查詢"></label><label>散步時間<select id="road-budget"><option value="30">30分鐘</option><option value="60" selected>60分鐘</option><option value="90">90分鐘</option><option value="custom">自訂</option></select></label><label>自訂分鐘<input id="custom-budget" type="number" min="10" max="480" value="120"></label><label>終點<select id="road-end"><option value="open">最後一站</option><option value="return">回到起點</option><option value="station">指定車站（外部導航）</option></select></label><label>候選策略<select id="road-preference"><option value="near">少走路：鄰近優先</option><option value="more">多景點：小園區優先</option></select></label><button id="geolocate">取得我的位置</button></div><div class="toolbar"><button id="generate-road" class="primary">規劃／重新計算步行路線</button><button id="retry-road">重試道路服務</button></div><p class="small">先以鄰近距離挑候選，再用 FOSSGIS OSRM 步行路網計算清單順序；非全域最佳。每站停留15分鐘為本站建議。開放時間、入口、階梯與通行限制可能未確認。</p><div id="road-result" aria-live="polite"></div>`;
return `<div class="route-panel" id="walk-panel"><p class="eyebrow">Your walking notes</p><h2>${C.route==='collection'?'手動散步收藏':C.route==='recommend'?'銀杏散步路線推薦':'我的散步清單'}</h2>${f}<p class="small">${C.route==='manual'?(C.maxStops?'最多5個景點。':'自行選點。')+'直線距離÷每分鐘80公尺為估算，不含道路繞行與停留。':C.route==='collection'?'自行排序收藏，不計算沒有證據的距離或時間。':'清單可以排序，變更後請重新計算。'}</p><ol id="route-list" class="route-list"></ol><div id="route-summary" class="route-summary"></div><div class="toolbar"><button id="clear-route">清空清單</button><a id="external-route" class="button" target="_blank" rel="noopener noreferrer" hidden>Google 地圖步行導航</a>${C.music?'<button id="route-music">開始散步音樂</button>':''}</div>${C.lottery?'<div class="feature-panel"><h3>散步抽籤</h3><label>抽籤類型<select id="lottery-size"><option value="1">1站：攝影</option><option value="2">2站：短散步</option><option value="3">3站：漫遊</option></select></label><button id="lottery">抽一組</button><div id="lottery-preview"></div><button id="lottery-confirm" hidden>確認加入</button></div>':''}</div>`;
}
function sourcesMarkup(){return `<div class="feature-panel"><h2>資料來源與查核範圍</h2><p>${esc(D.sheetReadStatus)}</p><p>整理 ${D.built}；清冊查核 ${D.snapshot}。清冊保留41筆、原始18欄與原列號。入口更新不等於新觀測。共用地點與座標資料快照2026-10-02；不是本次重新實測日期。</p><p>等級：S 官方公園協會；A 官方日期觀測；B 官方但銀杏資料待確認；C 官方入口且無日期觀測；O 氣象廳標本尺度；T 第三方；X 失效／排除。等級不直接代表當季可用葉況。</p><p>${esc(C.footer)} · ${link(D.originalSheet,'指定原始資料表')}</p>${C.restricted?'':`<p>座標採課程查核的近似值／園區代表點，不推定入口或單株。氣象廳平年值：${link(D.jma.yellowSource,'黃葉11/23')}、${link(D.jma.fallSource,'落葉12/3')}。</p>`}${D.images.length?`<p>歷史景觀照片：${D.images.map(i=>`${link(i.file_page,'原圖')} · ${esc(i.author)} · ${link(i.license_url,i.license_short)} · 拍攝 ${esc(i.date_taken)}`).join('；')}。非當季狀態。</p>`:''}${C.route==='roads'?`<p>道路服務：${link('https://routing.openstreetmap.de/','FOSSGIS OSRM／OpenStreetMap')}。失敗時提供外部導航，不產生虛構道路距離。</p>`:''}<div class="source-grid">${D.sources.map(s=>`<details class="source-row"><summary>第${s.row_number}列 · ${esc(s.name)} <span class="badge">${esc(s.grade)}／${sourceType(s)}</span></summary>${Object.entries(s).map(([k,v])=>`<p><strong>${esc(k)}</strong>：${/url$/.test(k)?link(v):esc(v||'來源未提供')}</p>`).join('')}</details>`).join('')}</div></div>`;}
function history(p){return p.history.length?`<div class="notice small"><strong>歷史紀錄，非今年狀態</strong>${p.history.map(h=>`<p>${esc(h.date||'日期未提供')} · ${esc(h.status||h.note||h.finding||h.text||'歷史參考')} ${link(h.url,'歷史來源')}</p>`).join('')}</div>`:'<p class="small">尚無本景點日期實測；來源的舊年度文章只作歷史／候選。</p>';}
function timeline(p){return '<ol class="timeline">'+stages.map(s=>`<li><strong>${s}</strong>來源未提供<br>日期／來源未提供</li>`).join('')+'</ol>';}
function card(p){return `<article class="card ${state.selected===p.id?'selected':''}" data-card="${p.id}"><button class="card-title" data-open="${p.id}">${esc(p.name_zh)}</button><p class="small">${esc(p.name_ja)} · ${esc(p.area)}</p>${badge(p)}<p>${state.demo?'示例日 '+state.demoDate:'觀測日期：來源未提供'}</p><p class="small">${esc(p.source.grade)} · ${esc(p.source.operator)}<br>清冊查核 ${esc(p.source.audited_at)}，不是觀測日</p>${C.timeline?timeline(p)+history(p):''}<p class="small">${link(p.source.url,'來源入口（非實測）')}</p><div class="card-actions"><button data-open="${p.id}">詳情</button>${C.route?`<button data-add="${p.id}">${state.route.includes(p.id)?'已在清單':'加入散步'}</button>`:''}${C.passport||C.favorites?`<button data-fav="${p.id}" aria-pressed="${state.favorites.includes(p.id)}">${state.favorites.includes(p.id)?'已收藏':'收藏'}</button>`:''}</div></article>`;}
function render(){const list=visible();$('#result-count').textContent=list.length+' 個景點';$('#stats').innerHTML=[['收錄景點',C.speciesSwitch&&state.species==='cherry'?0:D.places.length],[state.demo?'示意見頃':'當季見頃',state.demo?list.filter(p=>stage(p)===3).length:0],[state.demo?'示意黃葉進行':'當季黃葉進行',state.demo?list.filter(p=>stage(p)===2).length:0],[C.status,state.demo||state.species==='cherry'?0:D.places.length]].map(x=>`<div><strong>${x[1]}</strong><small>${x[0]}</small></div>`).join('');
if(C.timeline)$('#stats').innerHTML=[['收錄景點',D.places.length],...stages.map(x=>[x,0]),[C.status,D.places.length]].map(x=>'<div><strong>'+x[1]+'</strong><small>'+esc(x[0])+'</small></div>').join('');$('#legend').innerHTML=(state.species==='cherry'?['つぼみ','開花','見頃','葉桜']:stages).map((s,i)=>`<span><i style="background:${colors[i]}"></i>${s}${C.theme==='travel'?'/'+ja[i]:''}</span>`).join('');
$('#cards').innerHTML=list.length?list.map(card).join(''):`<div class="empty"><h3>${state.species==='cherry'?'櫻花：尚無資料':'沒有符合篩選的景點'}</h3><p>${state.species==='cherry'?'指定表沒有可用櫻花景點或觀測，沒有以銀杏資料代替。':'請放寬條件或清除篩選。'}</p><button id="empty-clear">清除篩選</button></div>`;
document.body.classList.toggle('cherry',state.species==='cherry');updateMap();renderFavorites();}
function details(p){return `<h2>${esc(p.name_zh)}</h2><p>${esc(p.name_ja)} · ${esc(p.type)}</p>${badge(p)}<dl class="definition"><dt>狀態日期</dt><dd>${state.demo?state.demoDate+'（示意）':'來源未提供；尚無當季日期觀測'}</dd><dt>地區</dt><dd>${esc(p.area)}</dd>${C.restricted?'':`<dt>座標</dt><dd>${p.lat}, ${p.lng}（近似／園區代表點）</dd><dt>交通</dt><dd>${esc(fact(p,'access'))}</dd><dt>開放</dt><dd>${esc(fact(p,'hours'))}${p.facts.hours_alt?'<br>另一官方說法：'+esc(p.facts.hours_alt):''}</dd><dt>費用</dt><dd>${esc(fact(p,'fee'))}</dd>`}<dt>銀杏／原表發現</dt><dd>${esc(p.proof_note)}</dd><dt>資料類型</dt><dd>${sourceType(p.source)} · ${esc(p.source.role)}</dd><dt>管理單位</dt><dd>${esc(p.source.operator)}</dd><dt>樹種</dt><dd>${esc(p.source.species)}</dd><dt>更新頻率</dt><dd>${esc(p.source.cadence)}</dd><dt>證據／發布日</dt><dd>${esc(p.source.evidence_date||'來源未提供')}（非當季實測日期）</dd><dt>查核</dt><dd>${esc(p.source.audited_at)}</dd></dl><div class="notice"><strong>資料注意事項</strong><p>${esc(p.source.caveat)}</p></div>${C.fixed?`<p>建議停留 ${p.staySuggestion}分鐘；${esc(p.activitySuggestion)}（本站規劃建議）。</p><ol class="stage-list">${stages.map((s,i)=>`<li style="border-color:${colors[i]}">${s}${stage(p)===i?' · 本示例':''}</li>`).join('')}</ol>`:''}${C.timeline?timeline(p):''}${history(p)}
${C.calendar?`<h3>七階段葉片成長圖例</h3><div class="growth">${['萌芽','嫩葉','成熟綠葉','轉黃','滿黃','落葉','休眠'].map(s=>`<div><span>${leafIcon}</span>${s}</div>`).join('')}</div><p class="small">概念圖例；沒有單株觀測，不從地面覆蓋推定樹冠葉況。</p><dl class="definition">${['葉色','葉片大小','扇形輪廓','裂片','葉脈','完整度','樹上葉量','地面覆蓋'].map(s=>`<dt>${s}</dt><dd>來源未提供</dd>`).join('')}</dl><p class="small">通常季節以東京標本平年11/23黃葉、12/3落葉作參考。交通出口與步行提示只依上列來源；無障礙、停車、單車、票價、末班車：來源未提供。</p>`:''}
<p>${link(p.source.url,'主要來源')} · ${link(p.source.evidence_url,'證據頁')}${p.source.extra_url?' · '+link(p.source.extra_url,'補充頁'):''}</p>${!C.restricted&&p.facts.sources?`<p>地點事實來源：${p.facts.sources.map(s=>link(typeof s==='string'?s:s.url,'官方原文')).join(' · ')}</p>`:''}
<div class="toolbar">${C.route?`<button data-add="${p.id}" class="primary">加入散步</button>`:''}${C.favorites||C.passport?`<button data-fav="${p.id}">${state.favorites.includes(p.id)?'取消收藏':'收藏'}</button>`:''}${C.passport?`<button data-visit="${p.id}">${state.visited.includes(p.id)?'取消已到訪':'標記已到訪'}</button>`:''}${!C.restricted?link('https://www.google.com/maps/search/?api=1&query='+encodeURIComponent(p.name_ja),'外部地圖'):''}</div>`;}
function openDetail(id,b){const p=D.places.find(p=>p.id===id);if(!p)return;state.selected=id;restoreFocus=b;if(map)map.setView([p.lat,p.lng],Math.max(map.getZoom(),12),{animate:false});render();if(C.theme==='studio'&&innerWidth>=1024){$('.right-column').hidden=false;$('#workspace').style.gridTemplateColumns='';$('#side-detail').hidden=false;$('#side-detail').innerHTML='<button id="close-side">關閉詳情</button>'+details(p);return;}$('#dialog-heading').textContent=p.name_zh;$('#dialog-content').innerHTML=details(p);if(!$('#detail').open)$('#detail').showModal();}
function clearFilters(){for(const k of ['q','region','status','grade','type','kind'])state[k]='';state.free=false;state.avenue=false;for(const s of ['#search','#region','#status','#grade','#type','#kind'])if($(s))$(s).value='';for(const s of ['#free','#avenue'])if($(s))$(s).checked=false;state.selected=null;render();fitMap(true);}
function goView(v){state.view=v;$$('.view').forEach(x=>x.hidden=x.id!==v+'-view');$$('[data-view]').forEach(b=>b.setAttribute('aria-pressed',b.dataset.view===v));if(C.theme==='studio'){if(v==='walk')$('#walk-view').append($('#walk-panel'));else $('#route-mount').append($('#walk-panel'));}if(v==='explore')requestAnimationFrame(resizeMap);if(v==='favorites')renderFavorites();if(v==='calendar')renderCalendar();if(v==='walk')renderRoute();}
function syncSearch(){if(C.theme!=='studio')return;const label=$('#search').closest('label'),slot=$('#mobile-search');if(!slot)return;if(innerWidth<768){slot.append(label);slot.hidden=false;}else{$('#filters').prepend(label);slot.hidden=true;if(innerWidth<1024)$('#workspace').style.gridTemplateColumns='';}}
function bind(){document.addEventListener('click',e=>{const b=e.target.closest('button,a');if(!b)return;
if(b.dataset.view){goView(b.dataset.view);if(b.dataset.scroll)$('#workspace').scrollIntoView();return;}
if(b.dataset.open)return openDetail(b.dataset.open,b);if(b.dataset.add)return addStop(b.dataset.add);if(b.dataset.fav)return toggleFavorite(b.dataset.fav);if(b.dataset.visit)return toggleVisit(b.dataset.visit);
if(b.dataset.remove){state.route=state.route.filter(x=>x!==b.dataset.remove);invalidateRoad();save();renderRoute();render();return;}
if(b.dataset.move){const i=state.route.indexOf(b.dataset.move),j=i+Number(b.dataset.direction);if(j>=0&&j<state.route.length){[state.route[i],state.route[j]]=[state.route[j],state.route[i]];invalidateRoad();save();renderRoute();}return;}
if(b.dataset.species){state.species=b.dataset.species;$$('[data-species]').forEach(x=>x.setAttribute('aria-pressed',x.dataset.species===state.species));clearFilters();return;}
if(b.dataset.mode){state.demo=b.dataset.mode==='demo';$('#demo-controls').hidden=!state.demo;$$('[data-mode]').forEach(x=>x.setAttribute('aria-pressed',x.dataset.mode===b.dataset.mode));clearFilters();renderRoute();return;}
if(b.dataset.layout){state.layout=b.dataset.layout;$('#map-shell').hidden=state.layout==='list';$('.left-column').hidden=state.layout==='map';$$('[data-layout]').forEach(x=>{x.setAttribute('aria-pressed',x.dataset.layout===state.layout);x.setAttribute('aria-selected',x.dataset.layout===state.layout);});requestAnimationFrame(resizeMap);return;}
switch(b.id){case 'empty-clear':case 'clear-filters':clearFilters();break;case 'filter-toggle':$('#filters').classList.toggle('mobile-closed');const open=!$('#filters').classList.contains('mobile-closed');b.setAttribute('aria-expanded',open);b.textContent=open?'收起篩選':'展開篩選';break;
case 'close-detail':$('#detail').close();break;case 'close-side':$('#side-detail').hidden=true;$('.right-column').hidden=true;$('#workspace').style.gridTemplateColumns='320px minmax(0,1fr)';resizeMap();break;case 'clear-route':state.route=[];invalidateRoad();save();renderRoute();render();break;
case 'recommend':recommend();break;case 'generate-road':case 'retry-road':generateRoad();break;case 'geolocate':locate();break;
case 'reset-passport':state.favorites=[];state.visited=[];save();renderFavorites();render();notify('收藏護照已清空。');break;
case 'lottery':drawLottery();break;case 'lottery-confirm':for(const id of lottery)if(!state.route.includes(id)&&state.route.length<5)state.route.push(id);lottery=[];$('#lottery-confirm').hidden=true;save();renderRoute();render();break;
case 'music':case 'route-music':toggleMusic();break;case 'motion':const off=!document.body.classList.contains('no-motion');document.body.classList.toggle('no-motion',off);b.textContent='動畫：'+(off?'關':'開');b.setAttribute('aria-pressed',!off);break;}
});
for(const [s,k] of [['#search','q'],['#region','region'],['#status','status'],['#grade','grade'],['#type','type'],['#sort','sort'],['#kind','kind']])if($(s))$(s).addEventListener(s==='#search'?'input':'change',e=>{state[k]=e.target.value;state.selected=null;render();fitMap(true);});
for(const [s,k] of [['#free','free'],['#avenue','avenue']])if($(s))$(s).addEventListener('change',e=>{state[k]=e.target.checked;render();});
$('#detail').addEventListener('click',e=>{if(e.target===$('#detail'))$('#detail').close();});
$('#detail').addEventListener('close',()=>{const a=document.activeElement;if(a&&a!==document.body&&a!==document.documentElement&&!$('#detail').contains(a))return;(restoreFocus?.isConnected?restoreFocus:$('[data-card="'+state.selected+'"] .card-title'))?.focus();});
if($('#demo-date'))$('#demo-date').addEventListener('input',e=>{const d=new Date('2026-10-10T12:00:00Z');d.setUTCDate(d.getUTCDate()+Number(e.target.value));state.demoDate=d.toISOString().slice(0,10);$('#demo-output').textContent=state.demoDate;render();renderRoute();});
if($('#calendar-date'))$('#calendar-date').addEventListener('change',renderCalendar);
window.addEventListener('resize',()=>{if(innerWidth>=1024&&state.layout!=='both'&&$('#map-shell')){state.layout='both';$('#map-shell').hidden=false;$('.left-column').hidden=false;}const r=$('#map')?.getBoundingClientRect();if(lastSize&&r&&(Math.abs(r.width-lastSize.width)>lastSize.width*.25||Math.abs(r.height-lastSize.height)>lastSize.height*.25))needsFit=true;clearTimeout(timer);timer=setTimeout(resizeMap,100);});
document.addEventListener('visibilitychange',()=>{if(!document.hidden)resizeMap();if(document.hidden&&musicPlaying)toggleMusic();});
}
function addStop(id){if(state.route.includes(id))return notify('此景點已在清單中。');if(C.maxStops&&state.route.length>=C.maxStops)return notify('最多5個景點，請先移除一站。');state.route.push(id);invalidateRoad();save();renderRoute();render();notify('已加入散步清單。');}
function invalidateRoad(){state.road=null;routeLayer?.clearLayers();if($('#road-result'))$('#road-result').textContent='順序已變更，請重新計算。';}
function hav(a,b){const r=Math.PI/180,z=Math.sin((b.lat-a.lat)*r/2)**2+Math.cos(a.lat*r)*Math.cos(b.lat*r)*Math.sin((b.lng-a.lng)*r/2)**2;return 6371000*2*Math.atan2(Math.sqrt(z),Math.sqrt(1-z));}
function routeUrl(list,origin){const q=new URLSearchParams({api:'1',travelmode:'walking'});if(list.length){q.set('origin',origin||list[0].name_ja);q.set('destination',list.at(-1).name_ja);const mids=origin?list.slice(0,-1):list.slice(1,-1);if(mids.length)q.set('waypoints',mids.map(p=>p.name_ja).join('|'));}return 'https://www.google.com/maps/dir/?'+q;}
function renderRoute(){if(!C.route||!$('#route-list'))return;const list=state.route.map(id=>D.places.find(p=>p.id===id));$('#route-list').innerHTML=list.length?list.map((p,i)=>`<li class="route-item"><strong>${esc(p.name_zh)}</strong>${badge(p)}${C.route==='recommend'?`<p class="small">${esc(p.activitySuggestion)} · 建議停留${p.staySuggestion}分鐘</p>`:''}<div class="controls"><button data-move="${p.id}" data-direction="-1" aria-label="${esc(p.name_zh)}上移" ${i===0?'disabled':''}>↑ 上移</button><button data-move="${p.id}" data-direction="1" aria-label="${esc(p.name_zh)}下移" ${i===list.length-1?'disabled':''}>↓ 下移</button><button data-remove="${p.id}">移除</button></div></li>`).join(''):'<li class="empty">尚未加入地點，請從卡片選擇。</li>';
let sum=0;if(C.route==='manual')for(let i=1;i<list.length;i++)sum+=hav(list[i-1],list[i]);
$('#route-summary').textContent=C.route==='manual'?`${list.length}站 · 直線距離估算 ${(sum/1000).toFixed(2)}公里 · 每分鐘80公尺估算 ${Math.ceil(sum/80)}分鐘，非道路步行時間。`:C.route==='recommend'?`${list.length}站 · 建議停留合計 ${list.reduce((a,p)=>a+p.staySuggestion,0)}分鐘；移動時間尚未計入。`:list.length+'個收藏地點';$('#external-route').hidden=!list.length||C.route==='collection';$('#external-route').href=routeUrl(list);drawRouteMap(list);}
function toggleFavorite(id){state.favorites=state.favorites.includes(id)?state.favorites.filter(x=>x!==id):[...state.favorites,id];save();render();if($('#detail').open)$('#dialog-content').innerHTML=details(D.places.find(p=>p.id===id));}
function toggleVisit(id){state.visited=state.visited.includes(id)?state.visited.filter(x=>x!==id):[...state.visited,id];save();renderFavorites();if($('#detail').open)$('#dialog-content').innerHTML=details(D.places.find(p=>p.id===id));}
function renderFavorites(){if(!C.favorites&&!C.passport)return;const list=D.places.filter(p=>state.favorites.includes(p.id));$('#favorites-view').innerHTML=`<div class="feature-panel"><h2>${C.passport?'我的銀杏護照':'收藏的秋色'}</h2><p>收藏${list.length}處${C.passport?' · 已到訪'+state.visited.length+'處':''}。${storageFailed?'本機儲存不可用。':'保存在本機瀏覽器，不需帳號或上傳。'}</p>${C.passport?'<button id="reset-passport">重設護照</button>':''}<div class="favorite-grid">${list.length?list.map(p=>`<div>${card(p)}${C.passport?`<button data-visit="${p.id}">${state.visited.includes(p.id)?'已到訪 · 取消':'標記已到訪'}</button>`:''}</div>`).join(''):'<p class="empty">尚未收藏景點。</p>'}</div></div>`;}
function recommend(){const r=$('#rec-region').value,s=$('#rec-status').value,pref=$('#rec-preference').value,budget=Number($('#rec-budget').value);let list=D.places.filter(p=>(!r||p.regionLabel===r)&&(!s||label(p)===s));const score=p=>Number(pref==='photo'?p.type==='銀杏大道':pref==='garden'?p.type==='庭園':p.type==='公園／園區');list.sort((a,b)=>score(b)-score(a));let used=0;state.route=[];for(const p of list){if(used+p.staySuggestion>budget||state.route.length>=5)break;used+=p.staySuggestion;state.route.push(p.id);}renderRoute();render();notify(state.route.length?'已產生停留計畫；交通請另查。':'沒有符合條件的景點，請放寬條件。');}
function drawLottery(){const n=Number($('#lottery-size').value),pool=visible().filter(p=>!state.route.includes(p.id));lottery=[];if(pool.length<n||state.route.length+n>5){$('#lottery-preview').textContent='符合篩選的景點或剩餘名額不足。';$('#lottery-confirm').hidden=true;return;}for(let i=0;i<n;i++)lottery.push(pool.splice(Math.floor(Math.random()*pool.length),1)[0].id);$('#lottery-preview').textContent='預覽：'+lottery.map(id=>D.places.find(p=>p.id===id).name_zh).join(' → ');$('#lottery-confirm').hidden=false;}
function toggleMusic(){if(musicPlaying){clearInterval(musicTimer);music?.suspend();musicPlaying=false;}else{const A=window.AudioContext||window.webkitAudioContext;if(!A)return notify('此瀏覽器不能播放合成音樂。');music=music||new A();music.resume().catch(()=>notify('請再按一次播放以允許音訊。'));let n=0;const notes=[261.63,329.63,392,523.25,392,329.63];const play=()=>{const o=music.createOscillator(),g=music.createGain(),t=music.currentTime;o.type='sine';o.frequency.value=notes[n++%notes.length];g.gain.setValueAtTime(0,t);g.gain.linearRampToValueAtTime(.035,t+.1);g.gain.exponentialRampToValueAtTime(.001,t+1.15);o.connect(g);g.connect(music.destination);o.start(t);o.stop(t+1.2);};play();musicTimer=setInterval(play,1200);musicPlaying=true;}if($('#music')){$('#music').textContent=musicPlaying?'停止散步音樂':'播放散步音樂';$('#music').setAttribute('aria-pressed',musicPlaying);}if($('#route-music'))$('#route-music').textContent=musicPlaying?'停止音樂':'開始散步音樂';}
function renderCalendar(){const date=$('#calendar-date').value,hs=D.places.flatMap(p=>p.history.map(h=>({p,h}))).filter(x=>/^\d{4}-\d{2}-\d{2}$/.test(x.h.date||''));hs.sort((a,b)=>Math.abs(new Date(a.h.date)-new Date(date))-Math.abs(new Date(b.h.date)-new Date(date)));$('#calendar-result').innerHTML='<div class="notice"><h3>選定日期：'+esc(date)+'</h3><p>此日尚無實測，不以舊資料代替。</p>'+(hs.length?'<p>最近<strong>歷史參考</strong>：'+esc(hs[0].p.name_zh)+' · '+esc(hs[0].h.date)+' · '+link(hs[0].h.url,'原文')+'</p>':'<p>沒有可用日期紀錄。</p>')+'</div>';}
function initMap(){if(C.map==='none')return;if(C.map==='leaflet'&&window.L){map=L.map('map',{trackResize:false,zoomControl:false,attributionControl:true}).setView([35.68,139.63],10);L.control.zoom({position:'topright'}).addTo(map);markerLayer=L.layerGroup().addTo(map);routeLayer=L.layerGroup().addTo(map);L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'<a href="https://www.openstreetmap.org/copyright" target="_blank" rel="noopener noreferrer">© OpenStreetMap contributors</a>'}).on('tileerror',()=>{if(++tileErrors===3){$('.map-label').textContent='底圖暫不可用；近似代表點標記與清單仍可使用。';notify('地圖底圖暫不可用，仍可使用景點標記與清單。');}}).addTo(map);map.on('moveend zoomend',updateMap);const reset=L.control({position:'topright'});reset.onAdd=()=>{const div=L.DomUtil.create('div');div.innerHTML='<button aria-label="顯示全部景點" id="map-reset">↺</button>';L.DomEvent.disableClickPropagation(div);div.firstChild.onclick=()=>{state.selected=null;fitMap(true);render();};return div;};reset.addTo(map);fitMap();}else{if(C.map==='leaflet')$('.map-label').textContent='地圖元件不可用，改顯示位置示意與清單。';$('#map').classList.add('diagram');updateMap();}
new ResizeObserver(()=>{clearTimeout(timer);timer=setTimeout(resizeMap,80);}).observe($('#map'));resizeMap();}
function fitMap(all=false){if(!map)return;if(!all&&state.selected){const p=D.places.find(x=>x.id===state.selected);map.setView([p.lat,p.lng],12,{animate:false});return;}const chosen=state.route.map(id=>D.places.find(p=>p.id===id));const list=!all&&chosen.length>1?chosen:visible();if(list.length)map.fitBounds(list.map(p=>[p.lat,p.lng]),{padding:[48,48],maxZoom:13,animate:false});}
function resizeMap(){syncSearch();const el=$('#map');if(!el)return;const r=el.getBoundingClientRect();if(r.width<1||r.height<1)return;if(map){map.invalidateSize({animate:false,pan:false});if(needsFit){needsFit=false;fitMap();}}lastSize={width:r.width,height:r.height};updateMap();}
function updateMap(){if(C.map==='leaflet'&&window.L&&!map)return;if(C.map==='none'||!$('#map'))return;const list=visible();if(map){markerLayer.clearLayers();const groups=[];for(const p of list){const xy=map.latLngToContainerPoint([p.lat,p.lng]),size=map.getSize();if(xy.x<26||xy.y<26||xy.x>size.x-26||xy.y>size.y-26)continue;let g=groups.find(g=>Math.hypot(xy.x-g.x,xy.y-g.y)<54);if(g){g.items.push(p);g.x=(g.x*(g.items.length-1)+xy.x)/g.items.length;g.y=(g.y*(g.items.length-1)+xy.y)/g.items.length;}else groups.push({items:[p],x:xy.x,y:xy.y});}
for(const g of groups){const p=g.items[0],pos=map.containerPointToLatLng([g.x,g.y]),multi=g.items.length>1,title=multi?g.items.map(x=>x.name_zh).join('、'):p.name_zh;const html=`<button class="map-marker ${multi?'cluster':''} ${state.selected===p.id?'selected':''}" data-marker="${multi?'cluster':p.id}" aria-label="${esc(title)}${multi?'，放大':'，'+esc(label(p))}">${multi?g.items.length+'＋':C.theme==='night'?leafIcon:D.places.indexOf(p)+1}</button>`;const m=L.marker(pos,{icon:L.divIcon({className:'leaflet-marker-icon',html,iconSize:[46,46],iconAnchor:[23,23]}),keyboard:false}).addTo(markerLayer);m.on('click',()=>{if(multi){map.fitBounds(g.items.map(p=>[p.lat,p.lng]),{padding:[65,65],maxZoom:map.getZoom()+3,animate:false});}else openDetail(p.id,m.getElement()?.querySelector('button'));});}
}else{const w=$('#map').clientWidth;if(w<1)return;const cols=w<450?3:5,row=Math.ceil(list.length/cols),height=Math.max(innerWidth<768?380:600,row*65+55);$('#map').style.height=height+'px';$('#map').innerHTML='<span class="diagram-region" style="top:10px;left:12px">東京東部｜東京中心｜東京西部｜多摩地區（示意）</span>'+list.map((p,i)=>`<button class="map-marker ${state.selected===p.id?'selected':''}" data-diagram="${p.id}" data-marker="${p.id}" aria-label="${esc(p.name_zh)}，${esc(label(p))}" style="left:${(i%cols+.5)*w/cols-23}px;top:${55+Math.floor(i/cols)*65}px">${D.places.indexOf(p)+1}</button>`).join('');$$('[data-diagram]').forEach(b=>b.onclick=()=>openDetail(b.dataset.diagram,b));}
if(C.theme==='night'&&map){$('#map-summary')?.remove();const p=D.places.find(p=>p.id===state.selected);if(p){const box=document.createElement('div');box.className='map-summary';box.id='map-summary';box.innerHTML=`<h3>${esc(p.name_zh)}</h3>${badge(p)}<p>日期：來源未提供</p><div class="toolbar"><button data-open="${p.id}">詳情</button><button data-fav="${p.id}">收藏</button><button data-add="${p.id}">加入</button></div>`;$('#map').append(box);L.DomEvent.disableClickPropagation(box);}}}
function drawRouteMap(list){if(!map||!routeLayer||C.route==='roads')return;routeLayer.clearLayers();if(C.route==='manual'&&list.length>1)L.polyline(list.map(p=>[p.lat,p.lng]),{color:'#a97623',dashArray:'6 8',weight:3}).addTo(routeLayer);}
shell();
if(C.music){const p=document.createElement('p');p.className='small';p.textContent='散步音樂為本站原創合成旋律；需按播放才啟用，可隨時停止。';$('.hero-copy').append(p);}
if(D.images.length){const i=D.images[0],f=document.createElement('figure');f.className='photo';f.innerHTML=`<img src="${esc(i.thumburl)}" alt="明治神宮外苑歷史銀杏景觀照片，非當季葉況" loading="lazy"><figcaption>${esc(i.place)} · 歷史照片 ${esc(i.date_taken)} · ${esc(i.author)} · ${link(i.license_url,i.license_short)} · ${link(i.file_page,'原圖')}</figcaption>`;$('#sources-view').firstElementChild.prepend(f);f.querySelector('img').onerror=()=>{f.querySelector('img').remove();f.insertAdjacentHTML('afterbegin','<p>照片暫不可用，請查看原圖連結。</p>');};}
window.SITE_QA={state,data:D,visible,resizeMap,stage,musicPlaying:()=>musicPlaying,map:()=>map};
})();
