/* 東京銀杏散步圖 — 資料檔
 * 來源：老師指定資料表 tokyo_ginkgo_sources_2026-09-29（sheet.csv）、
 *       學生 BRIEF 2026-10-01 核對事項、共用查核資料（2026-10-02，官方頁面）。
 * 規則：景點葉況只採「銀杏樹種＋特定地點＋觀測日期＋現場觀測」的資料；
 *       沒有符合條件的 2026 當季資料，一律顯示「尚無回報」。
 */
(function () {
  'use strict';

  var D1 = '2026-10-01'; // 學生 BRIEF 核對日期
  var D2 = '2026-10-02'; // 共用查核資料核對日期
  var JMA_FC = 'https://www.jma.go.jp/bosai/forecast/#area_type=offices&area_code=130000';
  var SHEET = 'https://docs.google.com/spreadsheets/d/1dx_41InyuuWuILc4ZHJW8tTZMVOCpIuSz-QzISzd7y0/edit?gid=164385659#gid=164385659';
  var TP_PR = 'https://www.tokyo-park.or.jp/association/assets/20251104_2025autumnleaves_pressrelease.pdf';

  function L(zh, en, ja) { return { zh: zh, en: en, ja: ja }; }
  // 欄位：s = 'ok'（已核對）| 'part'（部分待確認）| 'tbc'（待確認）；t = 三語文字；src = 來源網址陣列；d = 核對日期
  function F(s, t, src, d) { return { s: s, t: t, src: src || [], d: d || D2 }; }

  var WEATHER = F('tbc',
    L('靜態網站不提供天氣資料，請於出發前查看氣象廳東京都天氣預報。',
      'This static site carries no weather data. Check the JMA forecast for Tokyo before you go.',
      '静的サイトのため天気情報は掲載していません。出発前に気象庁の東京都の天気予報をご確認ください。'),
    [JMA_FC]);

  var WEAR = F('tbc',
    L('未核對可引用的官方穿著建議；請依出發前的氣象廳天氣預報（氣溫、降雨）自行準備。',
      'No official clothing advice was verified. Dress according to the JMA forecast (temperature, rain) before you go.',
      '引用できる公式の服装情報は未確認です。出発前に気象庁の予報（気温・降水）を見て準備してください。'),
    [JMA_FC]);

  function crowdTbc(url) {
    return F('tbc',
      L('官方未公布人潮資訊。', 'The official site publishes no crowd information.', '公式サイトに混雑情報の掲載はありません。'),
      [url]);
  }
  function eventTbc(url) {
    return F('tbc',
      L('本次查核未找到 2026 年秋季活動公告。', 'No 2026 autumn event announcement was found in this check.', '今回の確認では2026年秋のイベント告知は見つかりませんでした。'),
      [url]);
  }

  // 都立公園（S 級）葉況的共同說明
  function leafS(url) {
    return {
      date: null,
      nature: L('東京都公園協會園區頁（S 級）：本季尚無附日期的銀杏現場觀測',
        'Tokyo Park Association park page (grade S): no dated on-site ginkgo observation this season',
        '東京都公園協会の園ページ（S）：今季、日付付きのイチョウ現地観測なし'),
      note: L('2026-10-02 查核：園區頁沒有 2026 銀杏葉況；東京都公園協會尚未開設 2026 紅葉情報頁（2025 年舊專頁已失效）。',
        'Checked 2026-10-02: the park page has no 2026 ginkgo status, and the Tokyo Park Association has not opened a 2026 autumn-leaves page (the 2025 page is gone).',
        '2026-10-02確認：園ページに2026年のイチョウ情報はなく、東京都公園協会の2026年紅葉情報ページも未開設です（2025年の旧ページは404）。'),
      src: url, d: D2, history: []
    };
  }
  function leafC(url, extra) {
    return {
      date: null,
      nature: L('官方網站（無附日期的銀杏觀測）', 'Official site (no dated ginkgo observation)', '公式サイト（日付付きのイチョウ観測なし）'),
      note: extra || L('2026-10-02 查核：官方網站沒有 2026 年附日期的銀杏現場觀測。',
        'Checked 2026-10-02: the official site has no dated 2026 on-site ginkgo observation.',
        '2026-10-02確認：公式サイトに2026年の日付付きイチョウ現地観測はありません。'),
      src: url, d: D2, history: []
    };
  }

  var AREAS = [
    { id: 'toshin', name: L('都心', 'Central', '都心'),
      wards: L('千代田區、港區、新宿區', 'Chiyoda, Minato, Shinjuku', '千代田区・港区・新宿区') },
    { id: 'joto', name: L('城東', 'East', '城東'),
      wards: L('台東區、江東區', 'Taito, Koto', '台東区・江東区') },
    { id: 'johoku', name: L('城北', 'North', '城北'),
      wards: L('文京區、板橋區、練馬區', 'Bunkyo, Itabashi, Nerima', '文京区・板橋区・練馬区') },
    { id: 'josai', name: L('城西', 'West', '城西'),
      wards: L('澀谷區、杉並區、目黑區', 'Shibuya, Suginami, Meguro', '渋谷区・杉並区・目黒区') },
    { id: 'tama', name: L('多摩', 'Tama', '多摩'),
      wards: L('北多摩、南多摩（小金井、立川、國立、府中、八王子）', 'North and South Tama (Koganei, Tachikawa, Kunitachi, Fuchu, Hachioji)', '北多摩・南多摩（小金井・立川・国立・府中・八王子）') },
    { id: 'nishitama', name: L('西多摩', 'West Tama', '西多摩'),
      wards: L('秋留野市', 'Akiruno', 'あきる野市') }
  ];

  var SPOTS = [
    /* ---------------- 城東 ---------------- */
    {
      id: 'TKG-002', area: 'joto', grade: 'S', ll: [35.7130, 139.7724],
      name: L('上野恩賜公園', 'Ueno Onshi Park', '上野恩賜公園'),
      official: 'https://www.tokyo-park.or.jp/park/ueno/',
      ginkgo: L('銀杏資格來自 2025 年東京都公園協會紅葉名單；官方頁面未寫出園內銀杏的位置。',
        'Listed for ginkgo in the 2025 Tokyo Park Association autumn list; the official pages do not say where the trees stand.',
        '2025年の東京都公園協会紅葉名簿でイチョウとして掲載。園内のどこにあるかは公式ページに記載がありません。'),
      proof: { url: TP_PR,
        t: L('銀杏證明：東京都公園協會 2025 紅葉名單（2025-11-04）', 'Ginkgo proof: Tokyo Park Association 2025 autumn-leaves list (2025-11-04)', 'イチョウの根拠：東京都公園協会 2025年紅葉情報（2025-11-04）') },
      leaf: leafS('https://www.tokyo-park.or.jp/park/ueno/'),
      f: {
        hours: F('tbc',
          L('兩個官方頁面不一致：公園協會頁寫「常時開園」，東京都建設局頁寫「5:00–23:00（時間外禁止進入）」。',
            'Two official pages disagree: the park association says "always open"; the Bureau of Construction says 5:00–23:00 (no entry outside these hours).',
            '公式ページ間で食い違い：公園協会は「常時開園」、東京都建設局は「午前5時～午後11時（時間外は立入禁止）」。'),
          ['https://www.tokyo-park.or.jp/park/ueno/', 'https://www.kensetsu.metro.tokyo.lg.jp/jimusho/toubuk/ueno/kouenannai']),
        access: F('ok',
          L('JR、東京 Metro 銀座線・日比谷線「上野」站步行 2 分；京成「京成上野」站步行 1 分。',
            'Ueno Station (JR, Tokyo Metro Ginza and Hibiya lines): 2 min walk. Keisei-Ueno Station: 1 min walk.',
            'JR・東京メトロ銀座線・日比谷線「上野」徒歩2分、京成「京成上野」徒歩1分。'),
          ['https://www.tokyo-park.or.jp/park/ueno/']),
        rules: F('ok',
          L('免費（部分設施收費）。禁止無牽繩遛狗、無人機、滑板；請勿餵食動物。',
            'Free (some facilities charge). No off-leash dogs, drones or skateboards; do not feed animals.',
            '無料（一部有料施設あり）。ノーリードの犬の散歩、ドローン、スケートボードは禁止。動物への餌やりはご遠慮ください。'),
          ['https://www.kensetsu.metro.tokyo.lg.jp/jimusho/toubuk/ueno/rules']),
        event: eventTbc('https://www.tokyo-park.or.jp/park/ueno/'),
        crowd: crowdTbc('https://www.tokyo-park.or.jp/park/ueno/'),
        contact: F('ok', L('上野恩賜公園管理所 03-3828-5644', 'Ueno Park Office: 03-3828-5644', '上野恩賜公園管理所 03-3828-5644'),
          ['https://www.tokyo-park.or.jp/park/ueno/'])
      }
    },
    {
      id: 'TKG-013', area: 'joto', grade: 'S', ll: [35.7092, 139.7683],
      name: L('舊岩崎邸庭園', 'Kyu-Iwasaki-tei Gardens', '旧岩崎邸庭園'),
      official: 'https://www.tokyo-park.or.jp/park/kyu-iwasaki-tei/',
      ginkgo: L('官方植物清單列有銀杏，未寫出位置。', 'The official plant list includes ginkgo, without a location.', '公式の主な植物にイチョウが挙がりますが、場所の記載はありません。'),
      proof: null,
      leaf: leafS('https://www.tokyo-park.or.jp/park/kyu-iwasaki-tei/'),
      f: {
        hours: F('ok',
          L('9:00–17:00（16:30 停止入園）。休園：12/29–1/1。活動期間可能延長。',
            '9:00–17:00 (last entry 16:30). Closed 29 Dec–1 Jan. Hours may be extended during events.',
            '9:00～17:00（入園は16:30まで）。休園：12月29日～1月1日。イベント期間は延長の場合あり。'),
          ['https://www.tokyo-park.or.jp/park/kyu-iwasaki-tei/']),
        access: F('ok',
          L('東京 Metro 千代田線「湯島」站 1 號出口步行 3 分；銀座線「上野廣小路」站步行 10 分。',
            'Yushima Station (Chiyoda Line), Exit 1: 3 min walk. Ueno-hirokoji Station (Ginza Line): 10 min walk.',
            '東京メトロ千代田線「湯島」1番出口徒歩3分、銀座線「上野広小路」徒歩10分。'),
          ['https://www.tokyo-park.or.jp/park/kyu-iwasaki-tei/']),
        rules: F('ok',
          L('一般 400 円、65 歲以上 200 円。寵物不可入園（導盲犬等除外）；洋館與和館須脫鞋；禁菸酒；小學生以下須有監護人陪同；週六日與假日館內不可攝影。',
            'Adults ¥400, 65+ ¥200. No pets (assistance dogs excepted). Shoes off in the Western and Japanese houses. No smoking or alcohol. Children of primary-school age or younger must be accompanied. No photos inside the houses on weekends and holidays.',
            '一般400円、65歳以上200円。ペット不可（補助犬を除く）。洋館・和館は靴を脱ぐ。喫煙・飲酒不可。小学生以下のみの来園不可。土日祝は館内撮影不可。'),
          ['https://www.tokyo-park.or.jp/park/kyu-iwasaki-tei/', 'https://www.tokyo-park.or.jp/park/kyu-iwasaki-tei/news/2025/park_info_1.html']),
        event: F('ok',
          L('都立 9 庭園「紅葉巡禮集章」2026-10-10～12-06；「秋空の下で楽しむ旧岩崎邸庭園」10-18～11-29。這是活動日期，不是見頃日期。',
            'Nine metropolitan gardens autumn stamp rally: 2026-10-10 to 12-06. Garden event "秋空の下で楽しむ旧岩崎邸庭園": 10-18 to 11-29. These are event dates, not peak-viewing dates.',
            '都立9庭園「紅葉めぐりスタンプラリー」2026年10月10日～12月6日、「秋空の下で楽しむ旧岩崎邸庭園」10月18日～11月29日。イベント日程であり見頃の日付ではありません。'),
          ['https://www.tokyo-park.or.jp/special/9gardens_stamp/index.html', 'https://www.tokyo-park.or.jp/park/kyu-iwasaki-tei/']),
        crowd: crowdTbc('https://www.tokyo-park.or.jp/park/kyu-iwasaki-tei/'),
        contact: F('ok', L('舊岩崎邸庭園服務中心 03-3823-8340', 'Garden service center: 03-3823-8340', '旧岩崎邸庭園サービスセンター 03-3823-8340'),
          ['https://www.tokyo-park.or.jp/park/kyu-iwasaki-tei/'])
      }
    },
    {
      id: 'TKG-003', area: 'joto', grade: 'S', ll: [35.6752, 139.8085],
      name: L('木場公園', 'Kiba Park', '木場公園'),
      official: 'https://www.tokyo-park.or.jp/park/kiba/',
      ginkgo: L('園區頁沒有銀杏的記載；銀杏資格只見於 2025 年東京都公園協會紅葉名單。',
        'The park page does not mention ginkgo; only the 2025 Tokyo Park Association autumn list does.',
        '園ページにイチョウの記載はなく、2025年の紅葉名簿にのみイチョウと記載されています。'),
      proof: { url: TP_PR,
        t: L('銀杏證明：東京都公園協會 2025 紅葉名單（2025-11-04）', 'Ginkgo proof: Tokyo Park Association 2025 autumn-leaves list (2025-11-04)', 'イチョウの根拠：東京都公園協会 2025年紅葉情報（2025-11-04）') },
      leaf: leafS('https://www.tokyo-park.or.jp/park/kiba/'),
      f: {
        hours: F('ok',
          L('常時開園（服務中心與設施年末年始休息）。官方 2026-09-28 公告：木場ミドリアム因工程閉館。',
            'Always open (service center and facilities close over New Year). Official notice 2026-09-28: Kiba Midoriamu is closed for construction.',
            '常時開園（サービスセンター・施設は年末年始休業）。2026年9月28日付のお知らせで木場ミドリアムは工事のため閉館。'),
          ['https://www.tokyo-park.or.jp/park/kiba/']),
        access: F('ok',
          L('東京 Metro 東西線「木場」站步行 10 分；「清澄白河」站、都營新宿線「菊川」站步行 15 分。',
            'Kiba Station (Tozai Line): 10 min walk. Kiyosumi-shirakawa or Kikukawa stations: 15 min walk.',
            '東京メトロ東西線「木場」徒歩10分、「清澄白河」・都営新宿線「菊川」徒歩15分。'),
          ['https://www.tokyo-park.or.jp/park/kiba/']),
        rules: F('ok',
          L('免費（部分設施收費）。禁止高爾夫練習、正式球賽與滑板；寵物須牽繩；20 人以上團體須向服務中心申報。',
            'Free (some facilities charge). No golf practice, organised ball games or skateboarding. Dogs on leads. Groups of 20+ must notify the service center.',
            '無料（一部有料施設あり）。ゴルフ練習・球技の試合・スケートボード禁止。ペットはリード着用。20名以上の団体は届出。'),
          ['https://www.tokyo-park.or.jp/park/kiba/']),
        event: eventTbc('https://www.tokyo-park.or.jp/park/kiba/'),
        crowd: crowdTbc('https://www.tokyo-park.or.jp/park/kiba/'),
        contact: F('ok', L('木場公園服務中心 03-5245-1770', 'Kiba Park service center: 03-5245-1770', '木場公園サービスセンター 03-5245-1770'),
          ['https://www.tokyo-park.or.jp/park/kiba/'])
      }
    },

    /* ---------------- 都心 ---------------- */
    {
      id: 'TKG-011', area: 'toshin', grade: 'S', ll: [35.6737, 139.7559],
      name: L('日比谷公園', 'Hibiya Park', '日比谷公園'),
      official: 'https://www.tokyo-park.or.jp/park/hibiya/',
      ginkgo: L('「首賭けイチョウ」推定樹齡 400–500 年、幹圍 7 m，是公園的象徵；官方本文未寫出位置。',
        'The "Kubikake Ginkgo", estimated 400–500 years old with a 7 m trunk girth, is the park\'s symbol; the official text gives no location.',
        '「首賭けイチョウ」は推定樹齢400～500年・幹周り7mで公園のシンボル。本文に位置の記載はありません。'),
      proof: null,
      leaf: leafS('https://www.tokyo-park.or.jp/park/hibiya/'),
      f: {
        hours: F('ok',
          L('常時開園（服務中心 8:30–17:30，年末年始除外）。2026 年 10 月起再生整備工程中，大噴水、噴水廣場等區域不可進入。',
            'Always open (service center 8:30–17:30, except New Year). Renewal works as of October 2026: the Great Fountain and Fountain Plaza areas are closed.',
            '常時開園（サービスセンター8:30～17:30、年末年始を除く）。2026年10月時点で再生整備工事のため大噴水・噴水広場などは立入不可。'),
          ['https://www.tokyo-park.or.jp/park/hibiya/']),
        access: F('ok',
          L('東京 Metro「霞ケ関」站 B2 出口、「日比谷」站 A10・A14 出口即到；JR「有樂町」站步行 8 分。',
            'Kasumigaseki Station Exit B2 or Hibiya Station Exits A10/A14: right outside. Yurakucho Station (JR): 8 min walk.',
            '「霞ケ関」B2出口・「日比谷」A10・A14出口すぐ。JR「有楽町」徒歩8分。'),
          ['https://www.tokyo-park.or.jp/park/hibiya/']),
        rules: F('ok',
          L('免費（部分設施收費）。禁止球類、滑板、無人機與電動載具進入；寵物須牽繩；垃圾請帶走。',
            'Free (some facilities charge). No ball games, skateboards, drones or motorised vehicles. Dogs on leads. Take litter home.',
            '無料（一部有料施設あり）。球技・スケートボード・ドローン・電動機付き乗り物の乗り入れ禁止。ペットはリード着用。ゴミは持ち帰り。'),
          ['https://www.tokyo-park.or.jp/park/hibiya/']),
        event: eventTbc('https://www.tokyo-park.or.jp/park/hibiya/'),
        crowd: crowdTbc('https://www.tokyo-park.or.jp/park/hibiya/'),
        contact: F('ok', L('日比谷公園服務中心 03-3501-6428', 'Hibiya Park service center: 03-3501-6428', '日比谷公園サービスセンター 03-3501-6428'),
          ['https://www.tokyo-park.or.jp/park/hibiya/'])
      }
    },
    {
      id: 'TKG-005', area: 'toshin', grade: 'S', ll: [35.6555, 139.7480],
      name: L('芝公園', 'Shiba Park', '芝公園'),
      official: 'https://www.tokyo-park.or.jp/park/siba/',
      ginkgo: L('官方：園內各處有樟樹、櫸樹、銀杏等大樹（未寫出位置）。「もみじ谷」是楓樹區，不是銀杏。',
        'Official: large camphor, zelkova and ginkgo trees stand here and there (no location). Momijidani is the maple area, not ginkgo.',
        '公式：クスノキ・ケヤキ・イチョウなどの大木がところどころに（場所の記載なし）。もみじ谷はモミジの区画で、イチョウとは別です。'),
      proof: null,
      leaf: leafS('https://www.tokyo-park.or.jp/park/siba/'),
      f: {
        hours: F('ok', L('常時開園（服務中心與設施年末年始休息）。', 'Always open (service center and facilities close over New Year).', '常時開園（サービスセンター・施設は年末年始休業）。'),
          ['https://www.tokyo-park.or.jp/park/siba/']),
        access: F('ok',
          L('都營三田線「芝公園」「御成門」站步行 2 分；淺草線・大江戶線「大門」站步行 5 分；JR「濱松町」站步行 12 分。無停車場。',
            'Shibakoen or Onarimon stations (Mita Line): 2 min walk. Daimon Station: 5 min. Hamamatsucho (JR): 12 min. No parking.',
            '都営三田線「芝公園」「御成門」徒歩2分、「大門」徒歩5分、JR「浜松町」徒歩12分。駐車場なし。'),
          ['https://www.tokyo-park.or.jp/park/siba/']),
        rules: F('ok',
          L('免費（部分設施收費）。寵物須牽繩；攝影依申請規定，三腳架等器材可能需要占用許可。',
            'Free (some facilities charge). Dogs on leads. Photography follows the application rules; tripods and similar gear may need a permit.',
            '無料（一部有料施設あり）。ペットはリード着用。撮影は申請書類に従い、三脚等は占用許可の対象となる場合あり。'),
          ['https://www.tokyo-park.or.jp/park/siba/']),
        event: eventTbc('https://www.tokyo-park.or.jp/park/siba/'),
        crowd: crowdTbc('https://www.tokyo-park.or.jp/park/siba/'),
        contact: F('ok', L('芝公園服務中心 03-3431-4359', 'Shiba Park service center: 03-3431-4359', '芝公園サービスセンター 03-3431-4359'),
          ['https://www.tokyo-park.or.jp/park/siba/'])
      }
    },
    {
      id: 'TKG-009', area: 'toshin', grade: 'S', ll: [35.7037, 139.7135],
      name: L('戶山公園', 'Toyama Park', '戸山公園'),
      official: 'https://www.tokyo-park.or.jp/park/toyama/',
      ginkgo: L('官方植物清單列有銀杏，未寫出位置；公園分為箱根山地區與大久保地區。',
        'The official plant list includes ginkgo, without a location. The park has two parts: Hakoneyama and Okubo.',
        '主な植物にイチョウが挙がりますが場所の記載なし。園は箱根山地区と大久保地区に分かれます。'),
      proof: null,
      leaf: leafS('https://www.tokyo-park.or.jp/park/toyama/'),
      f: {
        hours: F('ok', L('常時開園（服務中心年末年始休息）。', 'Always open (service center closes over New Year).', '常時開園（サービスセンターは年末年始休業）。'),
          ['https://www.tokyo-park.or.jp/park/toyama/']),
        access: F('ok',
          L('東京 Metro 副都心線「西早稻田」站步行 6 分（大久保地區）／8 分（箱根山地區）；JR「新大久保」「高田馬場」站步行 10 分（大久保地區）。無停車場。',
            'Nishi-waseda Station (Fukutoshin Line): 6 min to the Okubo area, 8 min to Hakoneyama. Shin-Okubo or Takadanobaba (JR): 10 min to Okubo. No parking.',
            '副都心線「西早稲田」徒歩6分（大久保地区）・8分（箱根山地区）。JR「新大久保」「高田馬場」徒歩10分（大久保地区）。駐車場なし。'),
          ['https://www.tokyo-park.or.jp/park/toyama/']),
        rules: F('ok',
          L('免費。寵物須牽繩、糞便帶走；人多處請勿吸菸。',
            'Free. Dogs on leads; pick up after them. No smoking where people gather.',
            '無料。ペットはリード着用、フンは持ち帰り。人の集まる場所での喫煙はご遠慮ください。'),
          ['https://www.tokyo-park.or.jp/park/toyama/']),
        event: eventTbc('https://www.tokyo-park.or.jp/park/toyama/'),
        crowd: crowdTbc('https://www.tokyo-park.or.jp/park/toyama/'),
        contact: F('ok', L('戶山公園服務中心 03-3200-1702', 'Toyama Park service center: 03-3200-1702', '戸山公園サービスセンター 03-3200-1702'),
          ['https://www.tokyo-park.or.jp/park/toyama/'])
      }
    },
    {
      id: 'TKG-015', area: 'toshin', grade: 'A', ll: [35.6867, 139.7126],
      name: L('新宿御苑', 'Shinjuku Gyoen National Garden', '新宿御苑'),
      official: 'https://fng.or.jp/shinjuku/',
      ginkgo: L('官方 2025-11-28 文章提到園內各處銀杏，溫室附近是熱門拍攝點（過去紀錄）。',
        'The official 2025-11-28 article mentions ginkgo across the garden, with the area near the greenhouse a popular photo spot (past record).',
        '公式の2025年11月28日の記事では園内各所のイチョウ、温室付近が人気の撮影スポットと紹介（過去の記録）。'),
      proof: null,
      leaf: {
        date: null,
        nature: L('官方附日期現場觀測來源（A 級）：本季尚無銀杏文章',
          'Official dated on-site observation source (grade A): no ginkgo article this season',
          '公式・日付付き現地観測の情報源（A）：今季のイチョウ記事なし'),
        note: L('官方 2026-09-25 季節資訊未列銀杏葉況（2026-10-01 核對）；2026-10-02 再查，最新文章（至 10-01）也沒有銀杏。',
          'The official seasonal update of 2026-09-25 lists no ginkgo status (checked 2026-10-01). Rechecked 2026-10-02: no newer post (to 10-01) mentions ginkgo.',
          '公式の2026年9月25日の季節情報にイチョウの葉況なし（2026-10-01確認）。2026-10-02の再確認でも10月1日までの記事にイチョウなし。'),
        src: 'https://fng.or.jp/shinjuku/news/', d: D1 + ' / ' + D2,
        history: [{ date: '2025-11-28', url: 'https://fng.or.jp/shinjuku/2025/11/28/20251128_03/',
          t: L('官方記載園內銀杏「見頃」（上一季紀錄）', 'Official: ginkgo at peak across the garden (last season)', '公式：園内各所でイチョウがみごろ（前シーズンの記録）') }]
      },
      f: {
        hours: F('ok',
          L('10/1～3/14：9:00–16:30（16:00 停止入園）。休園：週一（遇假日順延至下一個平日）、12/29–1/3；秋季特別開園 11/1–11/15 期間無休。',
            '1 Oct–14 Mar: 9:00–16:30 (last entry 16:00). Closed Mondays (next weekday if Monday is a holiday) and 29 Dec–3 Jan. Open every day during the autumn special opening, 1–15 Nov.',
            '10月1日～3月14日：9:00～16:30（入園は16:00まで）。休園：月曜（休日の場合は翌平日）、12月29日～1月3日。秋の特別開園（11月1日～15日）は無休。'),
          ['https://fng.or.jp/shinjuku/2026/09/30/20260930-01/', 'https://fng.or.jp/shinjuku/guide/'], D1 + ' / ' + D2),
        access: F('ok',
          L('新宿門：新宿站南口步行 10 分、「新宿御苑前」站 1 號出口 5 分；千駄谷門：JR「千駄ヶ谷」站 5 分。大木戶門周邊施工，官方 2026-10-01 公告 10-06 起至 11 月下旬（預定）實施通行管制。',
            'Shinjuku Gate: 10 min from Shinjuku Station South Exit, 5 min from Shinjuku-gyoemmae Exit 1. Sendagaya Gate: 5 min from Sendagaya (JR). Official notice of 2026-10-01: traffic restrictions around Okido Gate from 10-06 to late November (planned).',
            '新宿門：新宿駅南口徒歩10分、新宿御苑前駅出口1徒歩5分。千駄ヶ谷門：JR千駄ヶ谷駅徒歩5分。2026年10月1日のお知らせ：大木戸門周辺で10月6日～11月下旬（予定）通行規制。'),
          ['https://fng.or.jp/shinjuku/access/', 'https://fng.or.jp/shinjuku/2026/10/01/20261001-01/'], D1 + ' / ' + D2),
        rules: F('ok',
          L('一般 500 円、65 歲以上與學生 250 円、國中以下免費。禁止攜入酒類、動物（輔助犬除外）、自行車、無人機；全面禁菸；禁止球類遊戲與搭帳篷。',
            'Adults ¥500; 65+ and students ¥250; junior-high age and under free. No alcohol, animals (assistance dogs excepted), bicycles or drones. No smoking. No ball games or tents.',
            '一般500円、65歳以上・学生250円、中学生以下無料。酒類・動物（補助犬を除く）・自転車・ドローンの持込み禁止。全面禁煙。ボール遊び・テント設置禁止。'),
          ['https://fng.or.jp/shinjuku/guide/', 'https://policies.env.go.jp/national-garden/shinjukugyoen/guide/rule/']),
        event: F('ok',
          L('早朝開園（7:00，只開新宿門）：2026-10-11、10-25、11-08、12-13 等日；秋季特別開園 11/1–11/15。',
            'Early-morning opening (7:00, Shinjuku Gate only): 2026-10-11, 10-25, 11-08, 12-13 and later dates. Autumn special opening: 1–15 Nov.',
            '早朝開園（7:00、新宿門のみ）：2026年10月11日・10月25日・11月8日・12月13日ほか。秋の特別開園11月1日～15日。'),
          ['https://fng.or.jp/shinjuku/2026/09/25/20260925-03/', 'https://fng.or.jp/shinjuku/guide/']),
        crowd: crowdTbc('https://fng.or.jp/shinjuku/'),
        contact: F('ok', L('新宿御苑服務中心 03-3350-0151', 'Shinjuku Gyoen service center: 03-3350-0151', '新宿御苑サービスセンター 03-3350-0151'),
          ['https://fng.or.jp/shinjuku/'])
      }
    },
    {
      id: 'TKG-023', area: 'toshin', grade: 'C', ll: [35.6739, 139.7199],
      name: L('明治神宮外苑 銀杏並木', 'Meiji Jingu Gaien Ginkgo Avenue', '明治神宮外苑 いちょう並木'),
      official: 'https://www.meijijingugaien.jp/walk/sight/season.html',
      ginkgo: L('官方：青山口至外苑中央廣場圓周道路的四列行道樹，300 m、146 株（歷史數值，不代表 2026 現況）。這裡不是明治神宮內苑。',
        'Official: four rows of street trees from the Aoyama entrance to the circular road, 300 m and 146 trees (historical figures, not a 2026 count). This is not the inner Meiji Jingu shrine.',
        '公式：青山口から外苑中央広場円周道路までの四列の並木、300m・146本（歴史的な数値で2026年の現況ではありません）。明治神宮内苑とは別です。'),
      proof: null,
      leaf: (function () {
        var lf = leafC('https://www.meijijingugaien.jp/walk/sight/season.html',
          L('2026-10-02 查核：官方網站沒有逐日銀杏葉況頁，也沒有 2026 年附日期的銀杏現場觀測；最近一篇銀杏文章是 2022-11-17（列於下方過去紀錄）。',
            'Checked 2026-10-02: the official site has no running ginkgo status page and no dated 2026 on-site ginkgo observation; its latest ginkgo post is from 2022-11-17 (listed below as a past record).',
            '2026-10-02確認：公式サイトに日々のイチョウ情報ページはなく、2026年の日付付きイチョウ現地観測もありません。最新のイチョウ記事は2022年11月17日です（下の過去の記録を参照）。'));
        lf.history = [{ date: '2022-11-17', url: 'https://www.meijijingugaien.jp/gaien-news/',
          t: L('官方「外苑便り」：「イチョウ並木が見頃です」（2022 年紀錄）', 'Official Gaien news: "The ginkgo avenue is at its peak" (2022 record)', '公式「外苑便り」：「イチョウ並木が見頃です」（2022年の記録）') }];
        return lf;
      })(),
      f: {
        hours: F('tbc', L('官方頁面未載開放時間。', 'The official pages state no opening hours.', '公式ページに開放時間の記載はありません。'),
          ['https://www.meijijingugaien.jp/walk/sight/season.html']),
        access: F('ok',
          L('JR「信濃町」「千駄ヶ谷」站；東京 Metro 銀座線「外苑前」「青山一丁目」站；都營大江戶線「國立競技場」站（官方未載步行時間）。',
            'Shinanomachi or Sendagaya (JR); Gaiemmae or Aoyama-itchome (Ginza Line); Kokuritsu-kyogijo (Oedo Line). Walking times are not stated officially.',
            'JR「信濃町」「千駄ヶ谷」、銀座線「外苑前」「青山一丁目」、大江戸線「国立競技場」（徒歩時間の記載なし）。'),
          ['https://www.meijijingugaien.jp/information/access-map.html']),
        rules: F('tbc', L('官方頁面未載入場費與利用規定。', 'No fee or visitor rules are stated on the official pages.', '公式ページに料金・利用ルールの記載はありません。'),
          ['https://www.meijijingugaien.jp/']),
        event: F('tbc', L('2026 年「神宮外苑銀杏祭」未見官方公告。', 'No official announcement of a 2026 Gaien ginkgo festival was found.', '2026年の「神宮外苑いちょう祭り」の公式告知は見つかりませんでした。'),
          ['https://www.meijijingugaien.jp/']),
        crowd: crowdTbc('https://www.meijijingugaien.jp/'),
        contact: F('ok', L('明治神宮外苑 03-3401-0312（代表）', 'Meiji Jingu Gaien: 03-3401-0312 (main line)', '明治神宮外苑 03-3401-0312（代表）'),
          ['https://www.meijijingugaien.jp/'])
      }
    },
    {
      id: 'TKG-026', area: 'toshin', grade: 'C', ll: [35.6941, 139.7431],
      name: L('靖國神社', 'Yasukuni Shrine', '靖國神社'),
      official: 'https://www.yasukuni.or.jp/',
      ginkgo: L('同一官方網域的公告提到「参道のイチョウ並木」；並木確切範圍未核實。境內為莊嚴的祭祀場所。',
        'A notice on the same official domain mentions the ginkgo avenue along the approach; its exact extent is not verified. The precincts are a solemn place of worship.',
        '同じ公式ドメインのお知らせに「参道のイチョウ並木」の記述。並木の範囲は未確認です。境内は厳粛な祭祀の場です。'),
      proof: { url: 'https://www.yasukuni.or.jp/news_detail.html?id=492',
        t: L('銀杏證明：官方公告（2023-09-06）', 'Ginkgo proof: official notice (2023-09-06)', 'イチョウの根拠：公式お知らせ（2023-09-06）') },
      leaf: leafC('https://www.yasukuni.or.jp/'),
      f: {
        hours: F('ok',
          L('開門 6:00；閉門 11・12・1・2 月 17:00，3–10 月 18:00。祭典與活動時可能變更。',
            'Gates open 6:00; close 17:00 in Nov–Feb and 18:00 in Mar–Oct. May change for ceremonies.',
            '開門6:00。閉門は1・2・11・12月17:00、3～10月18:00。祭典等で変更の場合あり。'),
          ['https://www.yasukuni.or.jp/']),
        access: F('ok',
          L('「九段下」站 1 號出口步行約 5 分；「飯田橋」「市ケ谷」站步行約 10 分。',
            'Kudanshita Station Exit 1: about 5 min walk. Iidabashi or Ichigaya: about 10 min.',
            '「九段下」出口1徒歩約5分、「飯田橋」「市ケ谷」徒歩約10分。'),
          ['https://www.yasukuni.or.jp/access.html']),
        rules: F('part',
          L('參拜費未載明（待確認）。禁止進入禁區、內苑騎自行車與遛狗、指定場所外吸菸、無人機、本殿與遊就館內攝影（部分區域除外）。',
            'Admission fee not stated (to be confirmed). No entering restricted areas, cycling or dog walking in the inner precinct, smoking outside designated areas, drones, or photos inside the main hall and Yushukan (some areas excepted).',
            '参拝料の記載なし（要確認）。立入禁止場所への侵入、内苑への自転車乗り入れ・犬の散歩、指定場所以外での喫煙、ドローン、本殿・遊就館内の撮影（一部除く）は禁止。'),
          ['https://www.yasukuni.or.jp/hope.html']),
        event: eventTbc('https://www.yasukuni.or.jp/'),
        crowd: crowdTbc('https://www.yasukuni.or.jp/'),
        contact: F('ok', L('靖國神社 03-3261-8326（代表）', 'Yasukuni Shrine: 03-3261-8326 (main line)', '靖國神社 03-3261-8326（代表）'),
          ['https://www.yasukuni.or.jp/'])
      }
    },
    {
      id: 'TKG-030', area: 'toshin', grade: 'B', ll: [35.6915, 139.7511],
      name: L('北之丸公園', 'Kitanomaru Park', '北の丸公園'),
      official: 'https://fng.or.jp/koukyo/',
      ginkgo: L('日本武道館前有「大イチョウ」，園內各處也有銀杏。本站只收北之丸公園：皇居外苑本身未證實有銀杏，也不是皇居東御苑。',
        'The "Big Ginkgo" stands in front of the Nippon Budokan, with more ginkgo across the park. Only Kitanomaru Park is listed here: the Kokyo Gaien itself is not proven for ginkgo, and this is not the East Gardens.',
        '日本武道館前に「大イチョウ」、園内各所にもイチョウ。本サイトは北の丸公園のみ掲載：皇居外苑はイチョウ未確認、皇居東御苑とも別です。'),
      proof: { url: 'https://fng.or.jp/koukyo/2023/11/24/kitanomarukouennnokouyou/',
        t: L('銀杏證明：國民公園協會文章（2023-11-24）', 'Ginkgo proof: National Gardens Association article (2023-11-24)', 'イチョウの根拠：国民公園協会の記事（2023-11-24）') },
      leaf: {
        date: null,
        nature: L('官方來源（B 級）：銀杏專項資料待補', 'Official source (grade B): ginkgo-specific data pending', '公式（B）：イチョウ専用の情報は未確認'),
        note: L('2026-10-02 查核：最新文章（至 10-01）沒有銀杏；09-19 季節文章只談花與果實。',
          'Checked 2026-10-02: no post up to 10-01 mentions ginkgo; the 09-19 seasonal essay covers flowers and berries only.',
          '2026-10-02確認：10月1日までの記事にイチョウなし。9月19日の季節記事は花と実のみ。'),
        src: 'https://fng.or.jp/koukyo/news/', d: D2,
        history: [
          { date: '2024-11-13', url: 'https://fng.or.jp/koukyo/2024/11/13/irodukukitanomarukouen/',
            t: L('官方：園內銀杏才剛開始轉色（上一季以前的紀錄）', 'Official: ginkgo had only just begun to turn (earlier season)', '公式：園内のイチョウは色づき始めたばかり（過去の記録）') },
          { date: '2023-11-24', url: 'https://fng.or.jp/koukyo/2023/11/24/kitanomarukouennnokouyou/',
            t: L('官方：大イチョウ見頃為 12 月上旬（2023 年文章）', 'Official: the Big Ginkgo peaks in early December (2023 article)', '公式：大イチョウの見ごろは12月上旬（2023年の記事）') }
        ]
      },
      f: {
        hours: F('ok',
          L('常時開放、無休（國家活動特別警備時可能限制使用）；22 時熄燈，夜間 22 時後請避免使用。',
            'Always open, no closing days (access may be restricted during state-event security). Lights off at 22:00; avoid use after about 22:00.',
            '常時開放・無休（国家行事等の特別警備時は利用規制あり）。22時消灯、22時ごろ以降の利用は控える。'),
          ['https://www.env.go.jp/garden/kokyogaien/2_guide/kitanomarukoen_00001.html']),
        access: F('ok',
          L('「九段下」站 2 號出口步行約 5 分；東西線「竹橋」站 1a／1b 出口步行約 8 分。',
            'Kudanshita Station Exit 2: about 5 min walk. Takebashi Station (Tozai Line) Exit 1a/1b: about 8 min.',
            '「九段下」2出口徒歩約5分、東西線「竹橋」1a・1b出口徒歩約8分。'),
          ['https://fng.or.jp/koukyo/access/']),
        rules: F('ok',
          L('免費。環境省紅葉期注意事項（2025-11-04）：全面禁菸、垃圾帶走、禁止用火、禁止長時間佔位、禁止樂器與擴音；20 人以上團體與攝影須申請。',
            'Free. Ministry of the Environment autumn notice (2025-11-04): no smoking, take litter home, no fire, no saving spots for long periods, no instruments or loudspeakers. Groups of 20+ and filming need a permit.',
            '無料。環境省「紅葉期散策利用の注意事項」（2025-11-04）：全面禁煙、ゴミ持ち帰り、火気厳禁、場所取り禁止、楽器・拡声器不可。20名以上の団体や撮影は申請が必要。'),
          ['https://www.env.go.jp/garden/kokyogaien/2_guide/kitanomarukoen_00001.html']),
        event: F('tbc',
          L('本次查核未找到北之丸公園 2026 年秋季活動公告。',
            'No 2026 autumn event announcement for Kitanomaru Park was found in this check.',
            '今回の確認では北の丸公園の2026年秋のイベント告知は見つかりませんでした。'),
          ['https://fng.or.jp/koukyo/']),
        crowd: crowdTbc('https://fng.or.jp/koukyo/'),
        contact: F('ok', L('國民公園協會 皇居外苑 03-3231-5509（平日 8:30–17:00）', 'National Gardens Association, Kokyo Gaien: 03-3231-5509 (weekdays 8:30–17:00)', '国民公園協会 皇居外苑 03-3231-5509（平日8:30～17:00）'),
          ['https://fng.or.jp/koukyo/'])
      }
    },
    {
      id: 'TKG-017', area: 'toshin', grade: 'A', ll: [35.6857, 139.7581],
      name: L('皇居東御苑', 'Imperial Palace East Gardens', '皇居東御苑'),
      official: 'https://www.kunaicho.go.jp/visit/higashigyoen/index.html',
      ginkgo: L('官方 2025-11-28 花だより照片標示「百人番所前のイチョウ」。東御苑不是皇居外苑或北之丸公園。',
        'The official 2025-11-28 garden diary shows "the ginkgo in front of the Hyakunin-bansho". The East Gardens are not the Kokyo Gaien or Kitanomaru Park.',
        '公式の2025年11月28日の花だよりに「百人番所前のイチョウ」の写真。東御苑は皇居外苑・北の丸公園とは別です。'),
      proof: null,
      leaf: {
        date: null,
        nature: L('官方附日期現場觀測來源（A 級）：本季尚無銀杏文章',
          'Official dated on-site observation source (grade A): no ginkgo entry this season',
          '公式・日付付き現地観測の情報源（A）：今季のイチョウ記事なし'),
        note: L('2026-10-02 查核：花だより最新一期為 2026-09-18，未列銀杏。',
          'Checked 2026-10-02: the latest garden diary (2026-09-18) does not mention ginkgo.',
          '2026-10-02確認：花だよりの最新号は2026年9月18日で、イチョウの記載はありません。'),
        src: 'https://www.kunaicho.go.jp/visit/higashigyoen/hanadayori/index.html', d: D2,
        history: [{ date: '2025-11-28', url: 'https://www.kunaicho.go.jp/visit/higashigyoen/hanadayori/20251128.html',
          t: L('官方：苑內銀杏等落葉樹轉色（上一季紀錄）', 'Official: ginkgo and other deciduous trees colouring (last season)', '公式：苑内各所でイチョウなどが紅葉（前シーズンの記録）') }]
      },
      f: {
        hours: F('ok',
          L('10 月 9:00–16:30（16:00 停止入園）；11–2 月 9:00–16:00（15:30 停止入園）。休園：週一、週五、12/28–1/3；國定假日開放（天皇誕生日除外），週一假日開放時改週二休。官方日曆：2026-10-02（五）、10-05（一）休園。',
            'October 9:00–16:30 (last entry 16:00); Nov–Feb 9:00–16:00 (last entry 15:30). Closed Mondays, Fridays and 28 Dec–3 Jan; open on national holidays except the Emperor\'s Birthday, with Tuesday closed instead when a Monday holiday opens. Official calendar: closed 2026-10-02 (Fri) and 10-05 (Mon).',
            '10月9:00～16:30（入園16:00まで）、11月～2月9:00～16:00（入園15:30まで）。休園：月・金曜、12月28日～1月3日。天皇誕生日以外の祝日は公開し、月曜が休日で公開の場合は火曜休園。休園日カレンダー：2026年10月2日（金）・5日（月）休園。'),
          ['https://www.kunaicho.go.jp/visit/higashigyoen/index.html', 'https://www.kunaicho.go.jp/visit/higashigyoen/gyoen-close.html']),
        access: F('ok',
          L('大手門：「大手町」站 C13a 出口步行約 5 分；平川門、北桔橋門：東西線「竹橋」站 1a 出口步行約 5 分。',
            'Otemon Gate: about 5 min from Otemachi Station Exit C13a. Hirakawamon and Kitahanebashimon gates: about 5 min from Takebashi Station Exit 1a.',
            '大手門：大手町駅C13a出口徒歩約5分。平川門・北桔橋門：竹橋駅1a出口徒歩約5分。'),
          ['https://www.kunaicho.go.jp/visit/higashigyoen/index.html']),
        rules: F('ok',
          L('免費、不需預約；入園時領取入園票，離園時繳回。禁止運動競技、採集植物、飲酒、商業攝影、攜帶動物（輔助犬除外）。',
            'Free, no booking. Take an entry token at the gate and return it when leaving. No sports, plant collecting, alcohol, commercial photography or animals (assistance dogs excepted).',
            '無料・予約不要。入園時に入園票を受け取り、退園時に返納。運動競技・植物の採取・飲酒・業としての撮影・動物の連行（補助犬を除く）は禁止。'),
          ['https://www.kunaicho.go.jp/visit/higashigyoen/pdf/koukaiyouryou.pdf']),
        event: eventTbc('https://www.kunaicho.go.jp/visit/higashigyoen/info/'),
        crowd: crowdTbc('https://www.kunaicho.go.jp/visit/higashigyoen/index.html'),
        contact: F('tbc', L('官方頁面未取得電話；請由宮內廳東御苑頁面確認。', 'No phone number found on the official pages; use the Imperial Household Agency East Gardens page.', '公式ページで電話番号を確認できませんでした。宮内庁の東御苑ページでご確認ください。'),
          ['https://www.kunaicho.go.jp/visit/higashigyoen/index.html'])
      }
    },

    /* ---------------- 城北 ---------------- */
    {
      id: 'TKG-018', area: 'johoku', grade: 'A', ll: [35.7202, 139.7452],
      name: L('小石川植物園', 'Koishikawa Botanical Garden', '小石川植物園'),
      official: 'https://koishikawa-bg.jp/',
      ginkgo: L('園內有植物學史上著名的「精子發現的銀杏」（雌株）。小石川植物園不是小石川後樂園。',
        'Home of the famous "sperm-discovery ginkgo" (a female tree). Koishikawa Botanical Garden is not Koishikawa Korakuen.',
        '植物学史に名高い「精子発見のイチョウ」（雌株）があります。小石川植物園と小石川後楽園は別の場所です。'),
      proof: null,
      leaf: {
        date: null,
        nature: L('官方附日期物種級觀察（A 級）：本季尚無銀杏文章',
          'Official dated species-level observation (grade A): no ginkgo post this season',
          '公式・日付付きの種別観察（A）：今季のイチョウ記事なし'),
        note: L('2026-10-02 查核：開花・紅葉狀況頁至 2026-10-01 的文章都沒有提到銀杏。',
          'Checked 2026-10-02: posts on the flowering and foliage page up to 2026-10-01 do not mention ginkgo.',
          '2026-10-02確認：開花・紅葉状況の2026年10月1日までの記事にイチョウの記載なし。'),
        src: 'https://koishikawa-bg.jp/kaikainfo/', d: D2,
        history: [{ date: '2025-11-19', url: 'https://koishikawa-bg.jp/kaika/5013/',
          t: L('官方：銀杏列在紅葉／黃葉植物中（看到黃葉不等於見頃）', 'Official: ginkgo listed among plants in autumn colour (yellow leaves do not mean peak)', '公式：紅葉・黄葉している植物にイチョウ（黄葉＝見頃ではない）') }]
      },
      f: {
        hours: F('ok',
          L('9:00–16:30（16:00 停止入園），開園期間 1/4–12/28。休園：週一（遇假日順延）。',
            '9:00–16:30 (last entry 16:00); open 4 Jan–28 Dec. Closed Mondays (next day if Monday is a holiday).',
            '9:00～16:30（入園16:00まで）、開園期間1月4日～12月28日。休園：月曜（祝日の場合は翌日）。'),
          ['https://koishikawa-bg.jp/overview/guide/']),
        access: F('ok',
          L('都營三田線「白山」站 A1 出口步行約 10 分；丸之內線「茗荷谷」站步行約 15 分。園內無停車位。',
            'Hakusan Station (Mita Line) Exit A1: about 10 min walk. Myogadani Station (Marunouchi Line): about 15 min. No parking.',
            '都営三田線「白山」A1出口徒歩約10分、丸ノ内線「茗荷谷」徒歩約15分。駐車場なし。'),
          ['https://koishikawa-bg.jp/access/']),
        rules: F('ok',
          L('大人 500 円、中小學生 150 円。禁止採集動植物（含掉落物）、攜帶寵物、吸菸飲酒、無人機；可在園內用餐，垃圾帶走；離園後不可再入園。',
            'Adults ¥500, school children ¥150. No collecting plants or animals (fallen items included), pets, smoking, alcohol or drones. Eating is allowed; take litter home. No re-entry.',
            '大人500円、小人150円。動植物の採集（落下物含む）・ペット・喫煙・飲酒・ドローン禁止。園内での食事は可（ゴミ持ち帰り）。再入園不可。'),
          ['https://koishikawa-bg.jp/overview/guide/']),
        event: eventTbc('https://koishikawa-bg.jp/'),
        crowd: crowdTbc('https://koishikawa-bg.jp/'),
        contact: F('tbc', L('本次讀取的官方頁面未載電話；請由官方網站確認。', 'No phone number on the official pages read; use the official site.', '今回読んだ公式ページに電話番号の記載なし。公式サイトでご確認ください。'),
          ['https://koishikawa-bg.jp/'])
      }
    },
    {
      id: 'TKG-040-hongo', area: 'johoku', grade: 'C', ll: [35.7131, 139.7606],
      name: L('東京大學 本鄉校區 銀杏並木', 'University of Tokyo Hongo Campus Ginkgo Avenue', '東京大学 本郷キャンパス 銀杏並木'),
      official: 'https://www.u-tokyo.ac.jp/ja/about/campus-guide/index.html',
      ginkgo: L('東大官方頁面提到「本郷キャンパスの銀杏並木」；東大網站「キミの東大」另寫「正門から続く銀杏並木」（自正門延伸）。本鄉、駒場與小石川植物園是不同地點。',
        'A University of Tokyo page names the Hongo campus ginkgo avenue; the university\'s "Kimino Todai" site adds that it continues from the main gate. Hongo, Komaba and the Koishikawa garden are separate places.',
        '東大公式ページに「本郷キャンパスの銀杏並木」。東大のサイト「キミの東大」には「正門から続く銀杏並木」とあります。本郷・駒場・小石川植物園は別の場所です。'),
      proof: [
        { url: 'https://www.u-tokyo.ac.jp/ja/about/campus-guide/1km_of_campus.html',
          t: L('銀杏證明：東大官方頁面', 'Ginkgo proof: University of Tokyo page', 'イチョウの根拠：東京大学公式ページ') },
        { url: 'https://kimino.ct.u-tokyo.ac.jp/kotohajime/hongo-campus/',
          t: L('位置說明：東大網站「キミの東大」', 'Location: University of Tokyo "Kimino Todai" site', '場所の説明：東京大学のサイト「キミの東大」') }
      ],
      leaf: leafC('https://www.u-tokyo.ac.jp/ja/about/campus-guide/index.html'),
      f: {
        hours: F('ok',
          L('本鄉校區參觀時間 7:00–18:00；正門平日 7:00–18:00、週六日與假日關閉（小門 7:00–24:30）；龍岡門常時開放。入學考試日等不可入校。',
            'Hongo visits 7:00–18:00. Main gate weekdays 7:00–18:00, closed weekends and holidays (side door 7:00–24:30); Tatsuoka Gate always open. No entry on exam days.',
            '本郷キャンパス見学は7時～18時。正門は平日7時～18時、土日祝は閉鎖（小扉7時～24時30分）、龍岡門は常時開放。入試日等は入構不可。'),
          ['https://www.u-tokyo.ac.jp/ja/about/campus-guide/public02_05.html']),
        access: F('ok',
          L('南北線「東大前」站步行 1 分；丸之內線「本鄉三丁目」站步行 8 分、大江戶線 6 分。',
            'Todaimae Station (Namboku Line): 1 min walk. Hongo-sanchome: 8 min (Marunouchi Line) or 6 min (Oedo Line).',
            '南北線「東大前」徒歩1分、「本郷三丁目」丸ノ内線徒歩8分・大江戸線徒歩6分。'),
          ['https://www.u-tokyo.ac.jp/ja/about/campus-guide/map01_02.html']),
        rules: F('part',
          L('入場費未載明（待確認）。進校時向門口警衛告知；15 人以上團體須於 7 天前網路登記；原則上不可進入建物；可拍照但不得刊登於出版品或社群；禁止商業攝影與婚紗攝影。',
            'Fee not stated (to be confirmed). Tell the guard at the gate; groups of 15+ register online 7 days ahead. Buildings are generally off limits. Photos are allowed but not for publication or social media; no commercial or wedding shoots.',
            '料金の記載なし（要確認）。入構時は門の警備員に告げる。15名以上の団体は7日前までにWeb登録。建物内は原則立入禁止。撮影は可だが刊行物・SNSへの掲載不可、商用撮影・前撮りは不可。'),
          ['https://www.u-tokyo.ac.jp/ja/about/campus-guide/public02_05.html']),
        event: eventTbc('https://www.u-tokyo.ac.jp/ja/about/campus-guide/index.html'),
        crowd: crowdTbc('https://www.u-tokyo.ac.jp/ja/about/campus-guide/index.html'),
        contact: F('ok', L('東京大學本部 03-3812-2111；本鄉校區參觀請用官方網路表單。', 'University of Tokyo main office: 03-3812-2111. For Hongo visits, use the official web form.', '東京大学 本部 03-3812-2111。本郷キャンパス見学はWebフォーム。'),
          ['https://www.u-tokyo.ac.jp/ja/about/campus-guide/public02_05.html'])
      }
    },
    {
      id: 'TKG-006', area: 'johoku', grade: 'S', ll: [35.7564, 139.6730],
      name: L('城北中央公園', 'Johoku Chuo Park', '城北中央公園'),
      official: 'https://www.tokyo-park.or.jp/park/johoku-chuo/',
      ginkgo: L('官方：「秋天銀杏並木漂亮轉色」，照片標示「イチョウ並木_正門」；並木確切位置未載明。園內也有櫸樹，兩者葉況不可混用。',
        'Official: "the ginkgo avenue colours beautifully in autumn"; a photo is captioned "ginkgo avenue, main gate". The exact position is not given. Zelkova grow here too; their status must not stand in for ginkgo.',
        '公式：「秋にはイチョウ並木が綺麗に色付きます」、写真表記「イチョウ並木_正門」。正確な位置の記載なし。ケヤキもあり、葉況を混同しないこと。'),
      proof: null,
      leaf: leafS('https://www.tokyo-park.or.jp/park/johoku-chuo/'),
      f: {
        hours: F('ok', L('常時開園（服務中心與設施年末年始休息）。', 'Always open (service center and facilities close over New Year).', '常時開園（サービスセンター・施設は年末年始休業）。'),
          ['https://www.tokyo-park.or.jp/park/johoku-chuo/']),
        access: F('ok',
          L('東武東上線「上板橋」站步行 15 分；東京 Metro「冰川台」站步行 20 分。',
            'Kami-itabashi Station (Tobu Tojo Line): 15 min walk. Hikawadai Station (Tokyo Metro): 20 min.',
            '東武東上線「上板橋」徒歩15分、東京メトロ「氷川台」徒歩20分。'),
          ['https://www.tokyo-park.or.jp/park/johoku-chuo/']),
        rules: F('ok',
          L('免費（部分設施收費）。寵物須牽繩；攝影須事先洽詢服務中心；約 20 人以上團體須於一週前提出申請。',
            'Free (some facilities charge). Dogs on leads. Ask the service center before filming. Groups of about 20+ apply a week ahead.',
            '無料（一部有料施設あり）。ペットはリード着用。撮影は事前協議。約20名以上の団体は1週間前までに申出票。'),
          ['https://www.tokyo-park.or.jp/park/johoku-chuo/']),
        event: eventTbc('https://www.tokyo-park.or.jp/park/johoku-chuo/'),
        crowd: crowdTbc('https://www.tokyo-park.or.jp/park/johoku-chuo/'),
        contact: F('ok', L('城北中央公園服務中心 03-3931-3650', 'Johoku Chuo Park service center: 03-3931-3650', '城北中央公園サービスセンター 03-3931-3650'),
          ['https://www.tokyo-park.or.jp/park/johoku-chuo/'])
      }
    },
    {
      id: 'TKG-010', area: 'johoku', grade: 'S', ll: [35.7648, 139.6295],
      name: L('光之丘公園', 'Hikarigaoka Park', '光が丘公園'),
      official: 'https://www.tokyo-park.or.jp/park/hikarigaoka/',
      ginkgo: L('官方：「いちょう並木」位於公園中央（賣店與觀賞池之間），由舊 Grant Heights 移植 28 株；另有「ふれあいの径」樹齡逾百年的銀杏 40 株。',
        'Official: the ginkgo avenue in the centre of the park (between the shop and the pond), 28 trees moved from the former Grant Heights; plus 40 ginkgo over 100 years old on the Fureai path.',
        '公式：「いちょう並木」は公園中央（売店と観賞池の間）、グラントハイツから移植した28本。ほかに「ふれあいの径」に樹齢100年超のイチョウ40本。'),
      proof: null,
      leaf: leafS('https://www.tokyo-park.or.jp/park/hikarigaoka/'),
      f: {
        hours: F('ok',
          L('常時開園（服務中心與設施年末年始休息）。屋敷森跡地週一休園、開放 10:00–15:30。',
            'Always open (service center and facilities close over New Year). The Yashikimori area closes Mondays and opens 10:00–15:30.',
            '常時開園（サービスセンター・施設は年末年始休業）。屋敷森跡地は月曜休園、10:00～15:30。'),
          ['https://www.tokyo-park.or.jp/park/hikarigaoka/']),
        access: F('ok',
          L('都營大江戶線「光が丘」站步行 8 分；東武東上線「成增」站步行 15 分。',
            'Hikarigaoka Station (Oedo Line): 8 min walk. Narimasu Station (Tobu Tojo Line): 15 min.',
            '大江戸線「光が丘」徒歩8分、東武東上線「成増」徒歩15分。'),
          ['https://www.tokyo-park.or.jp/park/hikarigaoka/']),
        rules: F('ok',
          L('免費（部分設施收費）。寵物須牽繩；個人紀念照與風景照不須申請；鳥類保護區內禁用三腳架。',
            'Free (some facilities charge). Dogs on leads. Personal and landscape photos need no permit; no tripods in the bird sanctuary.',
            '無料（一部有料施設あり）。ペットはリード着用。私的な記念写真・風景写真は申請不要。バードサンクチュアリ内は三脚禁止。'),
          ['https://www.tokyo-park.or.jp/park/hikarigaoka/']),
        event: eventTbc('https://www.tokyo-park.or.jp/park/hikarigaoka/'),
        crowd: crowdTbc('https://www.tokyo-park.or.jp/park/hikarigaoka/'),
        contact: F('ok', L('光之丘公園服務中心 03-3977-7638', 'Hikarigaoka Park service center: 03-3977-7638', '光が丘公園サービスセンター 03-3977-7638'),
          ['https://www.tokyo-park.or.jp/park/hikarigaoka/'])
      }
    },

    /* ---------------- 城西 ---------------- */
    {
      id: 'TKG-012', area: 'josai', grade: 'S', ll: [35.6717, 139.6965],
      name: L('代代木公園', 'Yoyogi Park', '代々木公園'),
      official: 'https://www.tokyo-park.or.jp/park/yoyogi/',
      ginkgo: L('官方秋季植物列有銀杏，未寫出位置。', 'The official autumn plant list includes ginkgo, without a location.', '秋の見ごろにイチョウが挙がりますが、場所の記載はありません。'),
      proof: null,
      leaf: leafS('https://www.tokyo-park.or.jp/park/yoyogi/'),
      f: {
        hours: F('ok', L('常時開園（服務中心與設施年末年始休息）。', 'Always open (service center and facilities close over New Year).', '常時開園（サービスセンター・施設は年末年始休業）。'),
          ['https://www.tokyo-park.or.jp/park/yoyogi/']),
        access: F('ok',
          L('JR「原宿」站、千代田線「代代木公園」站、「明治神宮前」站步行 3 分；小田急線「代代木八幡」站步行 6 分。',
            'Harajuku (JR), Yoyogi-koen or Meiji-jingumae stations: 3 min walk. Yoyogi-Hachiman (Odakyu Line): 6 min.',
            'JR「原宿」・「代々木公園」・「明治神宮前」徒歩3分、小田急線「代々木八幡」徒歩6分。'),
          ['https://www.tokyo-park.or.jp/park/yoyogi/']),
        rules: F('ok',
          L('免費（部分設施收費）。禁止滑板、球類練習、無人機、用火（含烤肉、煙火）、搭帳篷；寵物須牽繩。',
            'Free (some facilities charge). No skateboards, ball practice, drones, fires (BBQ, fireworks) or tents. Dogs on leads.',
            '無料（一部有料施設あり）。スケートボード・球技練習・ドローン・火気（BBQ・花火等）・テント禁止。ペットはリード着用。'),
          ['https://www.tokyo-park.or.jp/park/yoyogi/assets/files/yoyogi-kinshi20230919.pdf']),
        event: eventTbc('https://www.tokyo-park.or.jp/park/yoyogi/'),
        crowd: F('ok',
          L('官方：週六日與假日公園前道路擁擠，請搭大眾運輸。（無園內人潮資訊）',
            'Official: the road in front of the park is congested on weekends and holidays; use public transport. (No in-park crowd data.)',
            '公式：土日祝は公園前の道路が混雑するため公共交通機関を利用。（園内の混雑情報はなし）'),
          ['https://www.tokyo-park.or.jp/park/yoyogi/']),
        contact: F('ok', L('代代木公園服務中心 03-3469-6081', 'Yoyogi Park service center: 03-3469-6081', '代々木公園サービスセンター 03-3469-6081'),
          ['https://www.tokyo-park.or.jp/park/yoyogi/'])
      }
    },
    {
      id: 'TKG-040-komaba', area: 'josai', grade: 'C', ll: [35.6604, 139.6852],
      name: L('東京大學 駒場校區 銀杏並木', 'University of Tokyo Komaba Campus Ginkgo Avenue', '東京大学 駒場キャンパス 銀杏並木'),
      official: 'https://www.u-tokyo.ac.jp/ja/about/campus-guide/index.html',
      ginkgo: L('東大官方網站：「秋天銀杏並木把主要道路染成黃色」。與本鄉校區是不同地點。',
        'University of Tokyo site: "in autumn the ginkgo avenue turns the main street yellow". A separate place from Hongo.',
        '東京大学のサイト：「秋には銀杏並木がメインストリートを黄色に染め上げる」。本郷とは別の場所です。'),
      proof: { url: 'https://kimino.ct.u-tokyo.ac.jp/kotohajime/komaba-campus/',
        t: L('銀杏證明：東大官方網站', 'Ginkgo proof: University of Tokyo site', 'イチョウの根拠：東京大学のサイト') },
      leaf: leafC('https://www.u-tokyo.ac.jp/ja/about/campus-guide/index.html'),
      f: {
        hours: F('tbc', L('駒場 I 校區參觀規定與開門時間未核實，須另洽；駒場 II 校區平時不公開。', 'Komaba I visiting rules and gate hours are not verified (ask the campus); Komaba II is not open to the public.', '駒場Iの見学ルール・開門時間は未確認（別途問い合わせ）。駒場IIは通常非公開。'),
          ['https://www.u-tokyo.ac.jp/ja/about/campus-guide/public02_05.html']),
        access: F('ok',
          L('京王井之頭線「駒場東大前」站步行 0 分；小田急線「東北澤」站步行 8 分。',
            'Komaba-todaimae Station (Keio Inokashira Line): right outside. Higashi-kitazawa (Odakyu Line): 8 min walk.',
            '京王井の頭線「駒場東大前」徒歩0分、小田急線「東北沢」徒歩8分。'),
          ['https://www.u-tokyo.ac.jp/ja/about/campus-guide/map02_02.html']),
        rules: F('tbc', L('駒場校區的參觀規定未核實。', 'Komaba visiting rules are not verified.', '駒場キャンパスの見学ルールは未確認です。'),
          ['https://www.u-tokyo.ac.jp/ja/about/campus-guide/public02_05.html']),
        event: eventTbc('https://www.u-tokyo.ac.jp/ja/about/campus-guide/index.html'),
        crowd: crowdTbc('https://www.u-tokyo.ac.jp/ja/about/campus-guide/index.html'),
        contact: F('ok', L('東京大學本部 03-3812-2111', 'University of Tokyo main office: 03-3812-2111', '東京大学 本部 03-3812-2111'),
          ['https://www.u-tokyo.ac.jp/ja/about/campus-guide/list.html'])
      }
    },
    {
      id: 'TKG-008', area: 'josai', grade: 'S', ll: [35.6855, 139.6395],
      name: L('和田堀公園', 'Wadabori Park', '和田堀公園'),
      official: 'https://www.tokyo-park.or.jp/park/wadabori/',
      ginkgo: L('官方：鄰接的大宮八幡宮「神門的夫婦銀杏」轉黃時值得一看（神社是公園旁的另一設施）。2025 名單與善福寺川綠地合列一項。',
        'Official: the paired ginkgo at the gate of the adjoining Omiya Hachimangu shrine are worth seeing when yellow (the shrine is a separate site next to the park). Listed together with Zempukujigawa in 2025.',
        '公式：隣接する大宮八幡宮の「神門の夫婦銀杏」は黄葉が見もの（神社は公園に隣接する別施設）。2025名簿では善福寺川緑地と一列。'),
      proof: null,
      leaf: leafS('https://www.tokyo-park.or.jp/park/wadabori/'),
      f: {
        hours: F('ok', L('常時開園（服務中心與設施年末年始休息）。', 'Always open (service center and facilities close over New Year).', '常時開園（サービスセンター・施設は年末年始休業）。'),
          ['https://www.tokyo-park.or.jp/park/wadabori/']),
        access: F('ok',
          L('京王井之頭線「西永福」站步行 15 分；京王、關東巴士「都立和田堀公園」站下車。',
            'Nishi-eifuku Station (Keio Inokashira Line): 15 min walk. Keio or Kanto bus to "Toritsu Wadabori Koen".',
            '京王井の頭線「西永福」徒歩15分。京王バス・関東バス「都立和田堀公園」下車。'),
          ['https://www.tokyo-park.or.jp/park/wadabori/']),
        rules: F('ok',
          L('免費（部分設施收費）。寵物須牽繩；攝影依申請規定。',
            'Free (some facilities charge). Dogs on leads. Filming follows the application rules.',
            '無料（一部有料施設あり）。ペットはリード着用。撮影は申請書式に従う。'),
          ['https://www.tokyo-park.or.jp/park/wadabori/']),
        event: eventTbc('https://www.tokyo-park.or.jp/park/wadabori/'),
        crowd: crowdTbc('https://www.tokyo-park.or.jp/park/wadabori/'),
        contact: F('ok', L('善福寺川綠地服務中心 03-3313-4247（兼管和田堀公園）', 'Zempukujigawa service center (also covers Wadabori): 03-3313-4247', '善福寺川緑地サービスセンター 03-3313-4247（和田堀公園も担当）'),
          ['https://www.tokyo-park.or.jp/park/wadabori/'])
      }
    },
    {
      id: 'TKG-007', area: 'josai', grade: 'S', ll: [35.6920, 139.6305],
      name: L('善福寺川綠地', 'Zempukujigawa Ryokuchi', '善福寺川緑地'),
      official: 'https://www.tokyo-park.or.jp/park/zempukujigawa-ryokuchi/index.html',
      ginkgo: L('官方：秋天櫸樹、銀杏、唐楓、櫻樹等轉色（指全園，未寫出銀杏位置）。2025 名單與和田堀公園合列，不能假設各有獨立觀測。',
        'Official: zelkova, ginkgo, trident maple and cherry colour in autumn (whole park; no ginkgo location). Listed together with Wadabori in 2025, so separate observations cannot be assumed.',
        '公式：秋はケヤキ・イチョウ・トウカエデ・サクラなどが紅葉（園全体の記述で場所は未記載）。2025名簿は和田堀公園と一列で、個別観測は前提にできません。'),
      proof: null,
      leaf: leafS('https://www.tokyo-park.or.jp/park/zempukujigawa-ryokuchi/index.html'),
      f: {
        hours: F('ok', L('常時開園（服務中心年末年始休息）。', 'Always open (service center closes over New Year).', '常時開園（サービスセンターは年末年始休業）。'),
          ['https://www.tokyo-park.or.jp/park/zempukujigawa-ryokuchi/index.html']),
        access: F('ok',
          L('京王井之頭線「西永福」「濱田山」站步行 15 分；關東巴士「善福寺川緑地公園前」等站下車。',
            'Nishi-eifuku or Hamadayama stations (Keio Inokashira Line): 15 min walk. Kanto bus to "Zempukujigawa Ryokuchi Koen-mae" and other stops.',
            '京王井の頭線「西永福」「浜田山」徒歩15分。関東バス「善福寺川緑地公園前」ほか下車。'),
          ['https://www.tokyo-park.or.jp/park/zempukujigawa-ryokuchi/index.html']),
        rules: F('ok',
          L('免費（部分設施收費）。寵物須牽繩；攝影依申請規定。',
            'Free (some facilities charge). Dogs on leads. Filming follows the application rules.',
            '無料（一部有料施設あり）。ペットはリード着用。撮影は申請書式に従う。'),
          ['https://www.tokyo-park.or.jp/park/zempukujigawa-ryokuchi/index.html']),
        event: eventTbc('https://www.tokyo-park.or.jp/park/zempukujigawa-ryokuchi/index.html'),
        crowd: crowdTbc('https://www.tokyo-park.or.jp/park/zempukujigawa-ryokuchi/index.html'),
        contact: F('ok', L('善福寺川綠地服務中心 03-3313-4247', 'Zempukujigawa service center: 03-3313-4247', '善福寺川緑地サービスセンター 03-3313-4247'),
          ['https://www.tokyo-park.or.jp/park/zempukujigawa-ryokuchi/index.html'])
      }
    },
    {
      id: 'TKG-024', area: 'josai', grade: 'B', ll: [35.7007, 139.6248],
      name: L('大田黑公園', 'Otaguro Park', '大田黒公園'),
      official: 'https://ogikubo3gardens.jp/ootaguro/',
      ginkgo: L('杉並區官方：正門起 70 m 的石板園路兩側是樹齡百年的大銀杏並木。舊管理公司（箱根植木）的頁面已非現行來源。',
        'Suginami City: a 70 m stone path from the main gate is lined with 100-year-old ginkgo. The former manager\'s (Hakone Ueki) pages are no longer a current source.',
        '杉並区公式：正門から70mの園路の左右は樹齢100年の大イチョウ並木。旧管理会社（箱根植木）のページは現行の情報源ではありません。'),
      proof: null,
      leaf: {
        date: null,
        nature: L('官方來源（B 級）：銀杏專項資料待補', 'Official source (grade B): ginkgo-specific data pending', '公式（B）：イチョウ専用の情報は未確認'),
        note: L('2026-10-02 查核：公園網站最新消息（至 10-01）沒有葉況。',
          'Checked 2026-10-02: the park site\'s news up to 10-01 has no foliage item.',
          '2026-10-02確認：公園サイトの10月1日までのお知らせに葉況なし。'),
        src: 'https://ogikubo3gardens.jp/ootaguro/', d: D2, history: []
      },
      f: {
        hours: F('ok',
          L('9:00–17:00（16:30 停止入園）。休園：週三、12/29–1/1；休園日可能變更，請看官方網站。',
            '9:00–17:00 (last entry 16:30). Closed Wednesdays and 29 Dec–1 Jan; closing days may change, see the official site.',
            '9:00～17:00（入園16:30まで）。休園：水曜、12月29日～1月1日。変更の場合あり、最新はホームページで。'),
          ['https://www.city.suginami.tokyo.jp/s100/shisetsu/14632.html']),
        access: F('ok',
          L('JR、丸之內線「荻窪」站步行 10 分；無停車場，請勿開車前往。',
            'Ogikubo Station (JR, Marunouchi Line): 10 min walk. No parking; please do not come by car.',
            'JR・丸ノ内線「荻窪」徒歩10分。駐車場なし（車での来園はご遠慮ください）。'),
          ['https://ogikubo3gardens.jp/ootaguro/', 'https://www.city.suginami.tokyo.jp/s100/shisetsu/14632.html']),
        rules: F('part',
          L('入園費：兩個官方頁面都未載明（待確認）。點燈期間及前後不可外景拍攝與攝影。',
            'Admission fee: not stated on either official page (to be confirmed). No location shoots or photography during and around the illumination period.',
            '入園料：両公式ページとも記載なし（要確認）。ライトアップ期間とその前後はロケーション・写真撮影不可。'),
          ['https://www.city.suginami.tokyo.jp/s100/shisetsu/14632.html']),
        event: F('tbc', L('2026 年秋季點燈未見官方公告。', 'No official notice yet of a 2026 autumn illumination.', '2026年秋のライトアップの公式告知は見つかりませんでした。'),
          ['https://ogikubo3gardens.jp/ootaguro/']),
        crowd: crowdTbc('https://ogikubo3gardens.jp/ootaguro/'),
        contact: F('ok', L('管理事務室 03-3398-5814', 'Park office: 03-3398-5814', '管理事務室 03-3398-5814'),
          ['https://ogikubo3gardens.jp/ootaguro/'])
      }
    },

    /* ---------------- 多摩 ---------------- */
    {
      id: 'TKG-004', area: 'tama', grade: 'S', ll: [35.7155, 139.5189],
      name: L('小金井公園', 'Koganei Park', '小金井公園'),
      official: 'https://www.tokyo-park.or.jp/park/koganei/',
      ginkgo: L('官方秋季賞花資訊列有銀杏，未寫出位置。', 'The official autumn highlights include ginkgo, without a location.', '花の見ごろ情報（秋）にイチョウが挙がりますが、場所の記載はありません。'),
      proof: null,
      leaf: leafS('https://www.tokyo-park.or.jp/park/koganei/'),
      f: {
        hours: F('ok', L('常時開園（服務中心 8:30–17:30，年末年始休息）。', 'Always open (service center 8:30–17:30, closed over New Year).', '常時開園（サービスセンター8:30～17:30、年末年始休業）。'),
          ['https://www.tokyo-park.or.jp/park/koganei/']),
        access: F('ok',
          L('JR 中央線「武藏小金井」站搭西武巴士至「小金井公園西口」，或「東小金井」站搭 CoCo 巴士至「小金井公園入口」。官方未載步行時間。',
            'From Musashi-Koganei Station (JR Chuo Line) take a Seibu bus to "Koganei Koen Nishiguchi", or from Higashi-Koganei the CoCo bus to "Koganei Koen Iriguchi". Walking times are not stated.',
            'JR中央線「武蔵小金井」から西武バス「小金井公園西口」、「東小金井」からCoCoバス「小金井公園入口」。徒歩分数の記載なし。'),
          ['https://www.tokyo-park.or.jp/park/koganei/']),
        rules: F('ok',
          L('免費（部分設施收費）。垃圾帶走；園內禁止機車通行（含手推）；寵物須牽繩；20 人以上團體須提出申請。',
            'Free (some facilities charge). Take litter home. No motorbikes, even pushed. Dogs on leads. Groups of 20+ must apply.',
            '無料（一部有料施設あり）。ゴミは持ち帰り。バイク・スクーターの通行禁止（手押しも不可）。ペットはリード着用。20名以上は団体利用申出票。'),
          ['https://www.tokyo-park.or.jp/park/koganei/']),
        event: eventTbc('https://www.tokyo-park.or.jp/park/koganei/'),
        crowd: F('ok',
          L('官方：週六日與假日五日市街道塞車，請搭大眾運輸。（無園內人潮資訊）',
            'Official: Itsukaichi-kaido is congested on weekends and holidays; use public transport. (No in-park crowd data.)',
            '公式：土日祝は五日市街道が渋滞するため公共交通機関を利用。（園内の混雑情報はなし）'),
          ['https://www.tokyo-park.or.jp/park/koganei/']),
        contact: F('ok', L('小金井公園服務中心 042-385-5611', 'Koganei Park service center: 042-385-5611', '小金井公園サービスセンター 042-385-5611'),
          ['https://www.tokyo-park.or.jp/park/koganei/'])
      }
    },
    {
      id: 'TKG-041', area: 'tama', grade: 'C', ll: [35.6945, 139.4468],
      name: L('國立 大學通', 'Kunitachi Daigaku-dori', '国立 大学通り'),
      official: 'https://kunimachi.jp/',
      ginkgo: L('國立市觀光協會：秋天整條路被銀杏的黃色覆蓋。這條路也有櫻樹，櫻樹資訊不可代替銀杏。',
        'Kunitachi tourism association: in autumn the street is covered in ginkgo yellow. The street also has cherry trees, which must not stand in for ginkgo.',
        'くにたちNAVI：秋はイチョウの黄色で辺り一面が覆われる。通りには桜もあり、桜の情報をイチョウに代えないこと。'),
      proof: { url: 'https://kunimachi.jp/spot/daigakustreet/',
        t: L('銀杏證明：くにたちNAVI 官方頁面', 'Ginkgo proof: Kunitachi NAVI page', 'イチョウの根拠：くにたちNAVI') },
      leaf: leafC('https://kunimachi.jp/'),
      f: {
        hours: F('tbc', L('公共道路；官方未載開放時間。', 'A public street; no hours are stated officially.', '公道。公式に時間の記載はありません。'),
          ['https://kunimachi.jp/spot/daigakustreet/']),
        access: F('ok',
          L('官方：JR「國立」站往南直行的大道就是大學通；東京站至國立站搭 JR 中央線約 45 分。',
            'Official: Daigaku-dori is the wide street running straight south from Kunitachi Station (JR); about 45 min from Tokyo Station on the Chuo Line.',
            '公式：国立駅から真っすぐ南に伸びる大きな道が大学通り。東京駅から国立駅までJR中央線で約45分。'),
          ['https://kunimachi.jp/spot/daigakustreet/', 'https://kunimachi.jp/access/']),
        rules: F('tbc', L('官方未載利用規定（公共道路）。', 'No rules are stated officially (public street).', '公式に利用ルールの記載なし（公道）。'),
          ['https://kunimachi.jp/']),
        event: F('tbc',
          L('冬季點燈（站前通路 10 株銀杏、約 9 萬顆 LED）有介紹，但 2026 年日程未公布。',
            'A winter illumination (10 ginkgo near the station, about 90,000 LEDs) is described, but its 2026 dates are not announced.',
            '冬のイルミネーション（駅から続く道沿いのイチョウ10本・約9万個のLED）の紹介はあるが、2026年の日程は未発表。'),
          ['https://kunimachi.jp/spot/daigakustreet/']),
        crowd: crowdTbc('https://kunimachi.jp/'),
        contact: F('ok', L('國立市觀光まちづくり協會 042-574-1199', 'Kunitachi tourism association: 042-574-1199', '国立市観光まちづくり協会 042-574-1199'),
          ['https://kunimachi.jp/'])
      }
    },
    {
      id: 'TKG-014', area: 'tama', grade: 'A', ll: [35.7028, 139.4022],
      name: L('國營昭和紀念公園', 'Showa Kinen Park', '国営昭和記念公園'),
      official: 'https://www.showakinen-koen.jp/',
      ginkgo: L('官方：「カナール」與「かたらい」兩條銀杏並木；かたらい 98 株、300 m（カナール長度在官方頁面間有 200 m／150 m 的不一致）。官方例年說明「黃葉 10 月下旬～11 月下旬」，不是今年葉況。',
        'Official: two ginkgo avenues, Canal and Katarai; Katarai has 98 trees over 300 m (the Canal length differs between official pages, 200 m vs 150 m). The official usual season "yellow leaves late October to late November" is not this year\'s status.',
        '公式：カナールとかたらいの2つのイチョウ並木。かたらいは98本・300m（カナールの長さは公式ページ間で200m／150mと食い違い）。公式の例年表記「イチョウ（黄葉）10月下旬～11月下旬」は今年の葉況ではありません。'),
      proof: null,
      leaf: {
        date: null,
        nature: L('官方附日期現場快訊（A 級，花だより）：本季尚無銀杏',
          'Official dated on-site bulletin (grade A, Hanadayori): no ginkgo this season',
          '公式・日付付き現地情報（A、花だより）：今季のイチョウなし'),
        note: L('官方 2026-10-01 花だより列出當期花草（レモンブライト、コキア等），未列銀杏（2026-10-01 核對，10-02 再確認）。',
          'The official Hanadayori of 2026-10-01 lists current plants (Lemon Bright, kochia and others) but no ginkgo (checked 2026-10-01, rechecked 10-02).',
          '公式の2026年10月1日の花だよりは当期の草花（レモンブライト、コキアなど）を掲載し、イチョウはなし（2026-10-01確認、10-02再確認）。'),
        src: 'https://www.showakinen-koen.jp/hanadayori/', d: D1 + ' / ' + D2,
        history: [{ date: '2025-10-23～12-04', url: 'https://www.showakinen-koen.jp/hanadayori/page/3/',
          t: L('官方花だより連續多期有銀杏資訊（上一季紀錄；分頁位置會變動）', 'Official Hanadayori carried ginkgo items over several weeks (last season; page position shifts)', '公式花だよりに連続してイチョウ情報（前シーズン。ページ位置は変動）') }]
      },
      f: {
        hours: F('ok',
          L('10 月 9:30–17:00（みどりの文化ゾーン 8:30–17:00）；11–2 月 9:30–16:30。休園：12/31、1/1，1 月第 3 個週一至週五；天候不佳可能臨時休園。BRIEF（2026-10-01）確認官網開園資訊列有開放時間；上列時間取自 2026-10-02 讀取的官方頁面。',
            'October 9:30–17:00 (Midori-no-Bunka Zone 8:30–17:00); Nov–Feb 9:30–16:30. Closed 31 Dec, 1 Jan and Monday–Friday of the third week of January; may close in bad weather. The BRIEF (2026-10-01) confirmed that the official opening info lists hours; the hours above are from the official pages read on 2026-10-02.',
            '10月9:30～17:00（みどりの文化ゾーン8:30～17:00）、11月～2月9:30～16:30。休園：12月31日・1月1日、1月第3月曜～金曜。悪天候で臨時休園あり。BRIEF（2026-10-01）で公式の開園情報に開園時間の記載があることを確認。上記の時間は2026-10-02に読んだ公式ページによるものです。'),
          ['https://www.showakinen-koen.jp/park-information/schedule/', 'https://www.showakinen-koen.jp/'], D1 + ' / ' + D2),
        access: F('ok',
          L('西立川口：JR 青梅線「西立川」站約 2 分；立川口：JR「立川」站北口約 18 分；あけぼの口：立川站北口約 10 分。',
            'Nishi-Tachikawa Gate: about 2 min from Nishi-Tachikawa Station (JR Ome Line). Tachikawa Gate: about 18 min from Tachikawa Station North Exit. Akebono Gate: about 10 min.',
            '西立川口：JR青梅線「西立川」約2分。立川口：JR「立川」北口約18分。あけぼの口：立川駅北口約10分。'),
          ['https://www.showakinen-koen.jp/access/']),
        rules: F('ok',
          L('入園費大人 450 円、65 歲以上 210 円、國中以下免費（列對應依表格排列判讀）。禁止攜入刀械、煙火、爐具與燃料等；夜間點燈時日本庭園限制三腳架、禁止飲食與寵物。',
            'Admission: adults ¥450, 65+ ¥210, junior-high age and under free (column reading inferred from the table layout). No weapons, fireworks, stoves or fuel. During the evening illumination the Japanese garden limits tripods and bans food and pets.',
            '入園料 大人450円、シルバー210円、中学生以下無料（料金表の列対応は並びからの読み取り）。銃刀・花火・コンロ・燃料類などは持込み禁止。夜間ライトアップ時の日本庭園は三脚制限・飲食禁止・ペット不可。'),
          ['https://www.showakinen-koen.jp/park-information/price/', 'https://www.showakinen-koen.jp/park-information/park-rules/']),
        event: F('ok',
          L('「黃葉・紅葉祭＆秋の夜散歩 2026」：2026-10-29～11-29，點燈 16:30–20:30（かたらい並木、日本庭園、カナール；日本庭園 16:30 後另需觀賞券）。',
            '"Autumn Leaves Festival & Autumn Night Walk 2026": 2026-10-29 to 11-29, lights 16:30–20:30 (Katarai avenue, Japanese garden, Canal; the Japanese garden needs an extra ticket after 16:30).',
            '「黄葉・紅葉まつり＆秋の夜散歩2026」2026年10月29日～11月29日、点灯16:30～20:30（かたらいのイチョウ並木・日本庭園・カナール。日本庭園は16:30以降別途観賞券）。'),
          ['https://www.showakinen-koen.jp/autumn-night-walk/']),
        crowd: crowdTbc('https://www.showakinen-koen.jp/'),
        contact: F('ok', L('昭和紀念公園 042-528-1751', 'Showa Kinen Park: 042-528-1751', '国営昭和記念公園 042-528-1751'),
          ['https://www.showakinen-koen.jp/'])
      }
    },
    {
      id: 'TKG-025', area: 'tama', grade: 'C', ll: [35.6676, 139.4790],
      name: L('大國魂神社', 'Okunitama Shrine', '大國魂神社'),
      official: 'https://www.ookunitamajinja.or.jp/',
      ginkgo: L('神社官網：本殿後方有傳說樹齡約 1000 年的大銀杏。附近馬場大門的櫸樹並木不是銀杏。',
        'Shrine site: behind the main hall stands a great ginkgo said to be about 1,000 years old. The zelkova avenue at the nearby Baba-daimon is not ginkgo.',
        '神社公式：本殿裏に樹齢およそ1000年と伝わる大銀杏。近くの馬場大門のケヤキ並木はイチョウではありません。'),
      proof: null,
      leaf: leafC('https://www.ookunitamajinja.or.jp/mame/'),
      f: {
        hours: F('ok',
          L('開門：9/15–3/31 6:30–17:00；4/1–9/14 6:00–17:00。祭典與活動時可能變更。',
            'Gates: 15 Sep–31 Mar 6:30–17:00; 1 Apr–14 Sep 6:00–17:00. May change for ceremonies.',
            '開門：9月15日～3月31日 6:30～17:00、4月1日～9月14日 6:00～17:00。祭典等で変更あり。'),
          ['https://www.ookunitamajinja.or.jp/']),
        access: F('ok',
          L('京王線「府中」站南口步行 5 分；JR 南武線・武藏野線「府中本町」站步行 5 分。',
            'Fuchu Station South Exit (Keio Line): 5 min walk. Fuchu-hommachi (JR Nambu and Musashino lines): 5 min.',
            '京王線「府中」南口徒歩5分、JR南武線・武蔵野線「府中本町」徒歩5分。'),
          ['https://www.ookunitamajinja.or.jp/access/']),
        rules: F('tbc', L('參拜費與參拜規定：本次讀取的官方頁面未載明。', 'Fees and visitor rules: not stated on the official pages read.', '拝観料・参拝時の規則：今回読んだ公式ページに記載なし。'),
          ['https://www.ookunitamajinja.or.jp/']),
        event: F('tbc', L('秋季祭（9/27）已結束；未見與銀杏相關的 2026 秋季活動公告。', 'The autumn festival (9/27) is over; no 2026 autumn event related to the ginkgo was found.', '秋季祭（9月27日）は終了。イチョウに関する2026年秋の行事告知は見つかりませんでした。'),
          ['https://www.ookunitamajinja.or.jp/']),
        crowd: crowdTbc('https://www.ookunitamajinja.or.jp/'),
        contact: F('ok', L('大國魂神社 042-362-2130', 'Okunitama Shrine: 042-362-2130', '大國魂神社 042-362-2130'),
          ['https://www.ookunitamajinja.or.jp/'])
      }
    },
    {
      id: 'TKG-016', area: 'tama', grade: 'A', ll: [35.6520, 139.3004],
      name: L('八王子 甲州街道銀杏並木', 'Hachioji Koshu-kaido Ginkgo Avenue', '八王子 甲州街道いちょう並木'),
      official: 'https://www.ichou-festa.org/',
      ginkgo: L('官方：追分町至高尾站入口約 4 km、約 770 株，1927–1929 年植樹；黃葉情報的拍攝點是八王子市中央圖書館與多摩御陵入口交叉口。',
        'Official: about 4 km and about 770 trees from Oiwake-cho to the Takao Station entrance, planted 1927–1929. The leaf-report photos are taken at the Hachioji Central Library and the Tama Goryo entrance crossing.',
        '公式：追分町から高尾駅入口まで約4km・約770本、昭和2～4年に植樹。黄葉情報の撮影地点は八王子市中央図書館と多摩御陵入口交差点。'),
      proof: null,
      leaf: {
        date: '2026-09-22',
        nature: L('官方沿線照片更新（A 級）：未描述黃葉階段',
          'Official roadside photo update (grade A): no leaf stage stated',
          '公式の沿線写真更新（A）：黄葉の段階は未記載'),
        note: L('官方 2026-09-22 沿線照片更新；未描述黃葉階段，網站不推定葉況。',
          'Official roadside photos updated 2026-09-22; no leaf stage is described, so this site does not infer one.',
          '公式が2026年9月22日に沿線写真を更新。黄葉の段階は記載されておらず、本サイトは葉況を推定しません。'),
        src: 'https://www.ichou-festa.org/ichounews/', d: D1 + ' / ' + D2,
        history: []
      },
      f: {
        hours: F('tbc', L('並木是甲州街道（國道 20 號）沿線公共道路，官方未載時間限制。', 'The avenue lines a public road (Koshu-kaido, Route 20); no hours are stated officially.', '並木は甲州街道（国道20号）沿いの公道で、時間の記載はありません。'),
          ['https://www.ichou-festa.org/about']),
        access: F('part',
          L('並木沿甲州街道兩側延伸約 4 km；祭典期間沒有停車場，請搭大眾運輸。各站步行時間與路線巴士官方未載。',
            'The avenue runs about 4 km along both sides of the Koshu-kaido. No parking during the festival; use public transport. Walking times and bus routes are not stated officially.',
            '並木は甲州街道の両側に約4km。祭り期間は駐車場なし、公共交通機関を利用。駅からの徒歩時間・路線バスは公式に記載なし。'),
          ['https://www.ichou-festa.org/faq', 'https://www.ichou-festa.org/about']),
        rules: F('ok',
          L('祭典期間有交通管制；自行車請停在會場指定停車處。',
            'Traffic restrictions apply during the festival; park bicycles at the designated bicycle parking.',
            '祭り期間は交通規制あり。自転車は会場内指定の駐輪場を利用。'),
          ['https://www.ichou-festa.org/faq']),
        event: F('ok',
          L('第 47 回八王子銀杏祭：2026-11-21（六）9:00–16:30、11-22（日）9:00–16:00。祭典日期不是見頃日期。',
            '47th Hachioji Ginkgo Festival: 2026-11-21 (Sat) 9:00–16:30 and 11-22 (Sun) 9:00–16:00. Festival dates are not peak dates.',
            '第47回八王子いちょう祭り：2026年11月21日（土）9:00～16:30、22日（日）9:00～16:00。祭りの日程は見頃の日付ではありません。'),
          ['https://www.ichou-festa.org/event']),
        crowd: F('ok',
          L('官方：祭典期間擁擠並有道路封閉區段，沒有停車場。（無即時人潮資訊）',
            'Official: crowded during the festival, with road closures and no parking. (No live crowd data.)',
            '公式：祭り期間は混雑し通行止め区間あり、駐車場なし。（リアルタイムの混雑情報はなし）'),
          ['https://www.ichou-festa.org/faq']),
        contact: F('ok', L('八王子銀杏祭祭典委員會 042-668-8383', 'Hachioji Ginkgo Festival committee: 042-668-8383', '八王子いちょう祭り祭典委員会 042-668-8383'),
          ['https://www.ichou-festa.org/'])
      }
    },

    /* ---------------- 西多摩 ---------------- */
    {
      id: 'TKG-019', area: 'nishitama', grade: 'A', ll: [35.7218, 139.2174],
      name: L('廣德寺（秋留野）', 'Kotokuji Temple (Akiruno)', '広徳寺（あきる野）'),
      official: 'https://www.akirunokanko.com/',
      ginkgo: L('秋留野市官方：境內有銀杏巨樹。觀光協會紅葉文章中的石舟橋段落是楓樹，不適用於廣德寺銀杏。',
        'Akiruno City: a giant ginkgo stands in the temple grounds. The Ishifune Bridge section of the tourism reports is about maples and does not apply.',
        'あきる野市公式：境内にイチョウの巨樹。観光協会の紅葉情報の石舟橋の段落はモミジで、広徳寺のイチョウには当てはまりません。'),
      proof: null,
      leaf: {
        date: null,
        nature: L('在地觀光協會分地點巡查（A 級）：本季尚無紅葉文章',
          'Local tourism association spot reports (grade A): no autumn post this season',
          '地元観光協会の地点別レポート（A）：今季の紅葉記事なし'),
        note: L('2026-10-02 查核：のらぼう日記 2026 年尚無紅葉文章，最近的秋季系列是 2025-12-01。',
          'Checked 2026-10-02: the Norabo diary has no 2026 autumn post; the latest autumn series ended 2025-12-01.',
          '2026-10-02確認：のらぼう日記に2026年の紅葉記事はなく、直近の秋のシリーズは2025年12月1日が最後。'),
        src: 'https://www.akirunokanko.com/?cat=53', d: D2,
        history: [{ date: '2025-11-06', url: 'https://www.akirunokanko.com/?p=8712',
          t: L('拍攝日（11-08 發文）：銀杏轉色進行中，距見頃還差一些（上一季紀錄）', 'Photo date (posted 11-08): colouring progressing, not yet at peak (last season)', '撮影日（11月8日発信）：色づきが進み、見ごろまであと少し（前シーズン）') }]
      },
      f: {
        hours: F('tbc', L('參拜時間：官方頁面未核實。', 'Visiting hours: not verified on an official page.', '拝観時間：公式ページで未確認。'),
          ['https://www.city.akiruno.tokyo.jp/0000001442.html']),
        access: F('ok',
          L('JR「武藏五日市」站步行約 30 分；或搭巴士至「上町」下車步行約 15 分。',
            'Musashi-Itsukaichi Station (JR): about 30 min walk, or bus to "Kamicho" then about 15 min.',
            'JR「武蔵五日市」徒歩約30分、またはバス「上町」下車徒歩約15分。'),
          ['https://www.city.akiruno.tokyo.jp/0000001442.html']),
        rules: F('part',
          L('參拜費未核實。觀光協會提醒：請顧及附近居民與其他來訪者，遵守禮節。',
            'Fees not verified. The tourism association asks visitors to respect neighbours and other visitors.',
            '拝観料は未確認。観光協会：近隣の方やほかの来場者への配慮とマナーを守ってください。'),
          ['https://www.akirunokanko.com/?p=8712']),
        event: eventTbc('https://www.akirunokanko.com/'),
        crowd: crowdTbc('https://www.akirunokanko.com/'),
        contact: F('ok', L('秋留野市觀光協會 五日市觀光案內所 042-596-0514（週三公休）', 'Akiruno Tourism Association, Itsukaichi information office: 042-596-0514 (closed Wednesdays)', 'あきる野市観光協会 五日市観光案内所 042-596-0514（水曜定休）'),
          ['https://www.akirunokanko.com/'])
      }
    }
  ];

  var GRADES = {
    S: L('S：東京都公園協會（官方園區管理）', 'S: Tokyo Park Association (official park manager)', 'S：東京都公園協会（公式の園管理）'),
    A: L('A：官方或在地、附日期的現場觀測來源', 'A: official or local source with dated on-site observations', 'A：日付付き現地観測のある公式・地元の情報源'),
    B: L('B：官方來源，銀杏專項資料待補', 'B: official source, ginkgo-specific data pending', 'B：公式だがイチョウ専用の情報は未確認'),
    C: L('C：官方網站或入口，無附日期觀測', 'C: official site or entrance, no dated observation', 'C：公式サイト・入口、日付付き観測なし')
  };

  // 來源分類（BRIEF 必要功能 7）
  var SOURCES = {
    official: [
      { name: L('東京都公園協會', 'Tokyo Park Association', '東京都公園協会'), url: 'https://www.tokyo-park.or.jp/', g: 'S',
        note: L('都立公園入口；2026 紅葉情報頁尚未開設。', 'Metropolitan park portal; the 2026 autumn-leaves page has not opened yet.', '都立公園の入口。2026年の紅葉情報ページは未開設。') },
      { name: L('國營昭和紀念公園 花だより', 'Showa Kinen Park Hanadayori', '国営昭和記念公園 花だより'), url: 'https://www.showakinen-koen.jp/hanadayori/', g: 'A',
        note: L('附日期的園內植物快訊。', 'Dated in-park plant bulletins.', '日付付きの園内植物情報。') },
      { name: L('新宿御苑 最新消息', 'Shinjuku Gyoen news', '新宿御苑 お知らせ'), url: 'https://fng.or.jp/shinjuku/news/', g: 'A',
        note: L('國民公園協會的季節與植物文章。', 'National Gardens Association seasonal and plant posts.', '国民公園協会の季節・植物の記事。') },
      { name: L('八王子銀杏祭 黃葉情報', 'Hachioji Ginkgo Festival leaf reports', '八王子いちょう祭り 黄葉情報'), url: 'https://www.ichou-festa.org/ichounews/', g: 'A',
        note: L('附拍攝日期的沿線照片，官方表示不定期更新。', 'Roadside photos with shooting dates; updated irregularly.', '撮影日付きの沿線写真。不定期更新。') },
      { name: L('宮內廳 皇居東御苑 花だより', 'Imperial Household Agency, East Gardens diary', '宮内庁 皇居東御苑 花だより'), url: 'https://www.kunaicho.go.jp/visit/higashigyoen/hanadayori/index.html', g: 'A',
        note: L('附日期的園內植物紀錄。', 'Dated garden plant records.', '日付付きの園内植物の記録。') },
      { name: L('東京大學小石川植物園 開花・紅葉狀況', 'Koishikawa Botanical Garden flowering and foliage', '小石川植物園 開花・紅葉状況'), url: 'https://koishikawa-bg.jp/kaikainfo/', g: 'A',
        note: L('附日期的物種級觀察。', 'Dated species-level observations.', '日付付きの種別観察。') },
      { name: L('秋留野市觀光協會 のらぼう日記', 'Akiruno Tourism Association, Norabo diary', 'あきる野市観光協会 のらぼう日記'), url: 'https://www.akirunokanko.com/?cat=53', g: 'A',
        note: L('秋川溪谷分地點巡查，含廣德寺銀杏。', 'Spot-by-spot reports in the Akigawa valley, including Kotokuji\'s ginkgo.', '秋川渓谷の地点別レポート（広徳寺のイチョウを含む）。') },
      { name: L('明治神宮外苑', 'Meiji Jingu Gaien', '明治神宮外苑'), url: 'https://www.meijijingugaien.jp/walk/sight/season.html', g: 'C',
        note: L('銀杏並木介紹；無逐日葉況。', 'Ginkgo avenue introduction; no running status.', 'いちょう並木の紹介。日々の葉況はなし。') },
      { name: L('大田黑公園（荻窪三庭園）', 'Otaguro Park (Ogikubo gardens)', '大田黒公園（荻窪三庭園）'), url: 'https://ogikubo3gardens.jp/ootaguro/', g: 'B',
        note: L('現行官方入口。', 'Current official entrance.', '現行の公式入口。') },
      { name: L('大國魂神社', 'Okunitama Shrine', '大國魂神社'), url: 'https://www.ookunitamajinja.or.jp/mame/', g: 'C',
        note: L('大銀杏的地點介紹。', 'Location note on the great ginkgo.', '大銀杏の紹介。') },
      { name: L('靖國神社', 'Yasukuni Shrine', '靖國神社'), url: 'https://www.yasukuni.or.jp/', g: 'C',
        note: L('官方公告與境內照片入口。', 'Official notices and precinct photos.', '公式のお知らせと境内写真。') },
      { name: L('皇居外苑・北之丸公園（國民公園協會）', 'Kokyo Gaien / Kitanomaru Park (National Gardens Association)', '皇居外苑・北の丸公園（国民公園協会）'), url: 'https://fng.or.jp/koukyo/news/', g: 'B',
        note: L('四季消息；本站只收北之丸公園。', 'Seasonal news; this site lists Kitanomaru Park only.', '四季の情報。本サイトは北の丸公園のみ掲載。') },
      { name: L('東京大學 校區導覽', 'University of Tokyo campus guide', '東京大学 キャンパス案内'), url: 'https://www.u-tokyo.ac.jp/ja/about/campus-guide/index.html', g: 'C',
        note: L('本鄉與駒場的參觀入口。', 'Visiting information for Hongo and Komaba.', '本郷・駒場の見学案内。') },
      { name: L('くにたちNAVI（國立市觀光まちづくり協會）', 'Kunitachi NAVI (tourism association)', 'くにたちNAVI（国立市観光まちづくり協会）'), url: 'https://kunimachi.jp/', g: 'C',
        note: L('大學通介紹與在地消息。', 'Daigaku-dori introduction and local news.', '大学通りの紹介と地域の情報。') }
    ],
    aux: [
      { name: L('氣象廳 東京銀杏黃葉日（標本木）', 'JMA Tokyo ginkgo yellowing date (specimen tree)', '気象庁 いちょうの黄葉日（標本木）'), url: 'https://www.data.jma.go.jp/sakura/data/phn_012.html', g: 'O',
        note: L('東京觀測站標本木的日期，不是任何景點的葉況。平年值 11/23（1991–2020），2025 年 11/22，2026 年至 10-02 尚未觀測。',
          'Date for the specimen tree at JMA\'s Tokyo station, not any spot\'s status. Normal 11/23 (1991–2020); 2025: 11/22; 2026 not yet observed as of 10-02.',
          '東京の観測所の標本木の日付で、各スポットの葉況ではありません。平年値11月23日（1991～2020年）、2025年11月22日、2026年は10月2日時点で未観測。') },
      { name: L('氣象廳 東京銀杏落葉日（標本木）', 'JMA Tokyo ginkgo leaf-fall date (specimen tree)', '気象庁 いちょうの落葉日（標本木）'), url: 'https://www.data.jma.go.jp/sakura/data/phn_013.html', g: 'O',
        note: L('平年值 12/3，2025 年 12/4；指標本木約八成葉片落下的日子，不是全東京落葉完成日。',
          'Normal 12/3; 2025: 12/4. The day about 80% of the specimen tree\'s leaves have fallen, not the end of leaf fall across Tokyo.',
          '平年値12月3日、2025年12月4日。標本木の葉の約80%が落ちた日で、東京全体の落葉完了日ではありません。') },
      { name: L('氣象廳 東京都天氣預報', 'JMA weather forecast for Tokyo', '気象庁 東京都の天気予報'), url: JMA_FC, g: '',
        note: L('行前查看天氣與穿著用；本站不顯示天氣資料。', 'For weather and clothing before you go; this site shows no weather data.', '出発前の天気・服装の確認用。本サイトは天気を表示しません。') },
      { name: L('GO TOKYO 紅葉指南', 'GO TOKYO autumn leaves guide', 'GO TOKYO 紅葉ガイド'), url: 'https://www.gotokyo.org/jp/story/guide/autumn-leaves-forecast/index.html', g: 'C',
        note: L('東京官方旅遊網站的景點介紹；網址含 forecast 不等於有當日觀測。', 'Tokyo\'s official tourism site; "forecast" in the URL does not mean a daily observation.', '東京の公式観光サイトの紹介記事。URLにforecastとあっても当日観測ではありません。') },
      { name: L('tenki.jp 東京紅葉資訊', 'tenki.jp Tokyo autumn leaves', 'tenki.jp 東京都の紅葉情報'), url: 'https://tenki.jp/kouyou/3/16/', g: 'T',
        note: L('第三方整合，多樹種混合；示意照片不等於當日照片。', 'Third-party aggregator mixing species; sample photos are not same-day photos.', '第三者のまとめで樹種が混在。イメージ写真は当日の写真ではありません。') },
      { name: L('Weathernews 東京紅葉資訊', 'Weathernews Tokyo autumn leaves', 'ウェザーニュース 東京都の紅葉情報'), url: 'https://weathernews.jp/koyo/area/tokyo/', g: 'T',
        note: L('民間氣象平台；預報與回報不是官方實測。', 'Private weather platform; its forecasts and reports are not official measurements.', '民間の気象サービス。予想・リポートは公式の実測ではありません。') }
    ],
    sheet: [
      { name: L('指定來源資料表 tokyo_ginkgo_sources_2026-09-29', 'Assigned source sheet tokyo_ginkgo_sources_2026-09-29', '指定ソース表 tokyo_ginkgo_sources_2026-09-29'), url: SHEET, g: '',
        note: L('41 列來源，含來源分級、證據頁、資料日期、判讀說明、更新頻率、注意事項、樹種與查核日期。',
          '41 source rows with grade, evidence page, data date, finding, update cadence, caveats, species and audit date.',
          '41行の情報源。等級・根拠ページ・データ日付・判読・更新頻度・注意事項・樹種・確認日を含みます。') }
    ]
  };

  window.GINKGO_DATA = {
    D1: D1, D2: D2, JMA_FC: JMA_FC, SHEET: SHEET, TP_PR: TP_PR,
    AREAS: AREAS, SPOTS: SPOTS, GRADES: GRADES, SOURCES: SOURCES,
    WEATHER: WEATHER, WEAR: WEAR
  };
})();
